//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.CruzDelSur.Cliente.Carga
{


    public partial class _Default
    {
    }
}
