-- SOLICITUD DE COCINA
CREATE TABLE [dbo].[TA_SOLICITUDCOCINA](
	[INT_CODIGO_SOLICITUDCOCINA] [int] IDENTITY(1,1) NOT NULL,
	[INT_CODIGO_PROGRAMACION_RUTA] [int] NOT NULL,
	[DTE_FECHA_SOLICITUD] [smalldatetime] NULL, 
	[TIN_ESTADO] [tinyint] NOT NULL
 CONSTRAINT [PK_SOLPRODCOCINA] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_SOLICITUDCOCINA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
go

-- DETALLE DE SOLICITUD DE COCINA
CREATE TABLE [dbo].[TA_DET_SOLICITUDCOCINA](
	[INT_TA_DET_SOLICITUDCOCINA]  [int] IDENTITY(1,1) NOT NULL,
	[INT_CODIGO_SOLICITUDCOCINA] [int] NOT NULL,
	[INT_CODIGO_REFRIGERIO] [int] NOT NULL,
	[INT_CANTIDAD] [int] NULL,
 CONSTRAINT [PK_SOLPRODCOCINA] PRIMARY KEY CLUSTERED 
(
	[INT_TA_DET_SOLICITUDCOCINA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]



-- SOLICITUD INSUMO
CREATE TABLE [dbo].[TA_SOLICITUDINSUMO](
	[INT_CODIGO_SOLICITUDINSUMO] [int] IDENTITY(1,1) NOT NULL,
	[DTE_FECHA_SOLICITUD] [smalldatetime] NOT NULL,
	[INT_CODIGO_SOLICITUDCOCINA] [int] NULL,
	[TIN_ESTADO] [tinyint] NOT NULL,
 CONSTRAINT [PK_SOLICITUDINSUMO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_SOLICITUDINSUMO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


-- DETALLE SOLICITUD INSUMO
CREATE TABLE [dbo].[TA_DET_SOLICITUDINSUMO](
	[INT_TA_DET_SOLICITUDINSUMO] [int] IDENTITY(1,1) NOT NULL,
	[INT_CODIGO_SOLICITUDINSUMO] [int] NOT NULL,
	[INT_CODIGO_INSUMO] [int] NOT NULL,
	[INT_CANTIDAD] [int] NULL,
	[VCH_UNIDAD] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_TA_DET_SOLICITUDINSUMO] PRIMARY KEY CLUSTERED 
(
	[INT_TA_DET_SOLICITUDINSUMO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]





CREATE TABLE [dbo].[TA_GUIASALIDAINSUMO](
	[INT_CODIGO_GUIASALIDAINSUMO] [int] IDENTITY(1,1) NOT NULL,
	[INT_CODIGO_SOLICITUDINSUMO] [int] NOT NULL,
	[DTE_FECHA_GUIA] [smalldatetime] NOT NULL,
	[TIN_ESTADO] [tinyint] NOT NULL,
 CONSTRAINT [PK_GUIASALIDAINSUMO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_GUIASALIDAINSUMO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


-- DETALLE SOLICITUD INSUMO
CREATE TABLE [dbo].[TA_DET_GUIASALIDAINSUMO](
	[INT_DET_GUIASALIDAINSUMO] [int] IDENTITY(1,1) NOT NULL,
	[INT_CODIGO_GUIASALIDAINSUMO] [int] NOT NULL,
	[INT_CODIGO_INSUMO] [int] NOT NULL,
	[INT_CANTIDAD] [int] NULL,
	[VCH_UNIDAD] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_DET_GUIASALIDAINSUMO] PRIMARY KEY CLUSTERED 
(
	[INT_DET_GUIASALIDAINSUMO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


