USE [CSUR]
GO
/****** Object:  Table [dbo].[TA_ESTADOASIENTO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_ESTADOASIENTO](
	[INT_CODIGOESTASIENTO] [int] NOT NULL,
	[VCH_DETESTASIENTO] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_TA_ESTADOASIENTO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOESTASIENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_CARGO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_CARGO](
	[INT_CODIGOCARGO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.TA_CARGOS] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOCARGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_INSUMO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_INSUMO](
	[INT_CODIGO_INSUMO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_DESCRIPCION] [varchar](80) NOT NULL,
	[VCH_TIPO_UNIDAD] [varchar](60) NOT NULL,
	[DTE_FECHA_VENCIMIENTO] [smalldatetime] NOT NULL,
 CONSTRAINT [PK_INSUMO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_INSUMO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_GUIAREMISION]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_GUIAREMISION](
	[INT_CODIGO_GUIA] [int] IDENTITY(1,1) NOT NULL,
	[DTM_FECHA_TRASLADO] [datetime] NULL,
	[VCH_PUNTOPARTIDA] [varchar](50) NULL,
	[VCH_PUNTOLLEGADA] [varchar](50) NULL,
 CONSTRAINT [PK_TA_GUIAREMISION] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_GUIA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_DETALLESHOJAVIDA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_DETALLESHOJAVIDA](
	[INT_CODIGODETALLEHOJAVIDA] [int] IDENTITY(1,1) NOT NULL,
	[VCH_INSTITUCION] [nvarchar](max) NOT NULL,
	[DTE_DESDE] [datetime] NOT NULL,
	[DTE_HASTA] [datetime] NULL,
	[VCH_OBSERVACIONES] [nvarchar](max) NULL,
	[INT_CODIGOPERSONA] [int] NOT NULL,
 CONSTRAINT [PK_dbo.TA_DETALLESHOJAVIDA] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGODETALLEHOJAVIDA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[SP_LISTACARGASXFILTROS]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LISTACARGASXFILTROS]

(@VCH_NOM_CLIENTE AS VARCHAR(200),

@DTM_FECHA_DESDE AS DATETIME,

@DTM_FECHA_HASTA AS DATETIME,

@CHR_ESTADO AS CHAR(2))

AS

BEGIN

DECLARE @SQL_WHERE AS VARCHAR(255)

SET @SQL_WHERE = ''



IF(LTRIM(RTRIM(@VCH_NOM_CLIENTE)) <> '')

	SET @SQL_WHERE += ' AND (L.VCH_NOMBRES LIKE ''%' + @VCH_NOM_CLIENTE + '%'' OR L.VCH_APELLIDOS LIKE ''%' + @VCH_NOM_CLIENTE + '%'')'



IF(LTRIM(RTRIM(@CHR_ESTADO)) <> '')

	SET @SQL_WHERE += ' AND C.CHR_ESTADO = ''' + @CHR_ESTADO + ''''

	

IF(DATEPART(year, @DTM_FECHA_DESDE) <> 1900 AND DATEPART(year, @DTM_FECHA_HASTA) <> 1900)

	SET @SQL_WHERE += ' AND C.DTM_FECHA_REGISTRO >= ''' + CONVERT(VARCHAR, @DTM_FECHA_DESDE, 103) + ''' AND C.DTM_FECHA_REGISTRO <= ''' + CONVERT(VARCHAR, @DTM_FECHA_HASTA , 103) + ''' '

	

EXEC('SELECT C.INT_CODIGO_CARGA,C.DTM_FECHA_REGISTRO,C.VCH_OBSERVACION,C.VCH_CODIGO_SEGURIDAD,C.DBL_PESO,C.DBL_ANCHO,C.DBL_LARGO,C.DBL_PROFUNDIDAD,C.INT_TIPO_CARGA,C.INT_TIPO_PAGO,C.INT_CODIGO_PROGRAMACION_RUTA,C.INT_CODIGO_ALMACEN,C.VCH_CLIENTE_ORIGEN,C.
INT_CODIGO_GUIA,C.CHR_ESTADO,C.VCH_CLIENTE_DESTINO 

FROM TA_CARGA C 

INNER JOIN TA_PROGRAMACION_RUTA P ON C.INT_CODIGO_PROGRAMACION_RUTA = P.INT_CODIGO_PROGRAMACION_RUTA

INNER JOIN TA_CLIENTE L ON C.VCH_CLIENTE_ORIGEN = L.VCH_DOCUMENTO

WHERE 0=0 ' + @SQL_WHERE)

END
GO
/****** Object:  StoredProcedure [dbo].[SP_LISTACARGAENTREGADA]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LISTACARGAENTREGADA]    
(@VCH_DOC_CLIENTE AS VARCHAR(15) = NULL,    
@INT_DEPARTAMENTO AS INT = -1)    
AS    
BEGIN    
DECLARE @SQL_WHERE AS VARCHAR(255)    
    
IF(LTRIM(RTRIM(@VCH_DOC_CLIENTE)) <> '')    
 SET @SQL_WHERE = ' AND C.VCH_DOCUMENTO=''' + @VCH_DOC_CLIENTE + ''' '    
     
IF(@INT_DEPARTAMENTO <> -1)    
 SET @SQL_WHERE = ' AND R.INT_UBIGEO_ORIGEN=' + CAST(@INT_DEPARTAMENTO AS VARCHAR) + ' '    
     
EXEC('SELECT A.INT_CODIGO_CARGA, C.VCH_NOMBRES + '' '' + C.VCH_APELLIDOS CLIENTE_ORIGEN, U.VCH_NOMBRE DEPARTAMENTO,    
P.DTM_FECHA_ORIGEN,  TP.VCH_NOMBRE TIPO_PAGO    
FROM TA_CARGA A     
INNER JOIN TA_CLIENTE C ON A.VCH_CLIENTE_ORIGEN = C.VCH_DOCUMENTO    
INNER JOIN TA_PROGRAMACION_RUTA P ON A.INT_CODIGO_PROGRAMACION_RUTA = P.INT_CODIGO_PROGRAMACION_RUTA    
INNER JOIN TA_RUTA R ON P.INT_CODIGO_RUTA = R.INT_CODIGO_RUTA    
INNER JOIN TA_UBIGEO U ON U.INT_CODIGO_UBIGEO = R.INT_UBIGEO_ORIGEN    
LEFT JOIN TA_TIPO_PAGO TP ON A.INT_TIPO_PAGO = TP.INT_TIPO_PAGO WHERE A.CHR_ESTADO=''RC'' ' + @SQL_WHERE)    
END
GO
/****** Object:  StoredProcedure [dbo].[SP_OBTENERPAGOXCARGA]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_OBTENERPAGOXCARGA]
(@INT_CODIGO_CARGA AS INT)
AS 
BEGIN
SELECT DBL_MONTO,DTM_FECHA_REGISTRO,CHR_ESTADO,INT_CODIGO_CARGA FROM TA_PAGO WHERE INT_CODIGO_CARGA = @INT_CODIGO_CARGA
END
GO
/****** Object:  StoredProcedure [dbo].[SP_LISTAUTIL]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LISTAUTIL] 
(@CHR_TIPO_UTIL AS CHAR(1),
@CHR_ENTIDAD_UTIL AS CHAR(2))
AS
BEGIN

IF(@CHR_ENTIDAD_UTIL = 'ES')
	EXEC('SELECT CHR_ESTADO CHR_UTIL, VCH_NOMBRE FROM TA_ESTADO WHERE CHR_TIPO=''' + @CHR_TIPO_UTIL + ''' ORDER BY VCH_NOMBRE')

IF(@CHR_ENTIDAD_UTIL = 'UD')
EXEC('SELECT INT_CODIGO_UBIGEO CHR_UTIL, VCH_NOMBRE FROM TA_UBIGEO WHERE VCH_CODIGO_PROVINCIA=''000'' AND VCH_CODIGO_DISTRITO=''000'' ORDER BY VCH_NOMBRE')

IF(@CHR_ENTIDAD_UTIL = 'TC')
EXEC('SELECT INT_TIPO_CARGA CHR_UTIL, VCH_NOMBRE FROM TA_TIPO_CARGA ORDER BY VCH_NOMBRE')

IF(@CHR_ENTIDAD_UTIL = 'TP')
EXEC('SELECT INT_TIPO_PAGO CHR_UTIL, VCH_NOMBRE FROM TA_TIPO_PAGO ORDER BY VCH_NOMBRE')

IF(@CHR_ENTIDAD_UTIL = 'TM')
EXEC('SELECT INT_TIPO_MOVIMIENTO CHR_UTIL, VCH_NOMBRE FROM TA_TIPO_MOVIMIENTO ORDER BY VCH_NOMBRE')

IF(@CHR_ENTIDAD_UTIL = 'TS')
EXEC('SELECT INT_TIPO_SERVICIO CHR_UTIL, VCH_NOMBRE FROM TA_TIPO_SERVICIO ORDER BY VCH_NOMBRE')

IF(@CHR_ENTIDAD_UTIL = 'TT')
EXEC('SELECT INT_TIPO_TRANSPORTE CHR_UTIL, VCH_NOMBRE FROM TA_TIPO_SERVICIO ORDER BY VCH_NOMBRE')

END
GO
/****** Object:  StoredProcedure [dbo].[SP_BUSCAUTILXCODIGO]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_BUSCAUTILXCODIGO] 
(@CHR_CODIGO AS VARCHAR(5),
@CHR_ENTIDAD_UTIL AS CHAR(2))
AS
BEGIN

IF(@CHR_ENTIDAD_UTIL = 'ES')
	EXEC('SELECT CHR_ESTADO CHR_UTIL, VCH_NOMBRE FROM TA_ESTADO WHERE CHR_ESTADO=''' + @CHR_CODIGO + '''')

IF(@CHR_ENTIDAD_UTIL = 'UD')
EXEC('SELECT INT_CODIGO_UBIGEO CHR_UTIL, VCH_NOMBRE FROM TA_UBIGEO WHERE INT_CODIGO_UBIGEO=' + @CHR_CODIGO)

IF(@CHR_ENTIDAD_UTIL = 'TC')
EXEC('SELECT INT_TIPO_CARGA CHR_UTIL, VCH_NOMBRE FROM TA_TIPO_CARGA WHERE INT_TIPO_CARGA=' + @CHR_CODIGO)

IF(@CHR_ENTIDAD_UTIL = 'TP')
EXEC('SELECT INT_TIPO_PAGO CHR_UTIL, VCH_NOMBRE FROM TA_TIPO_PAGO WHERE INT_TIPO_PAGO=' + @CHR_CODIGO)

IF(@CHR_ENTIDAD_UTIL = 'TM')
EXEC('SELECT INT_TIPO_MOVIMIENTO CHR_UTIL, VCH_NOMBRE FROM TA_TIPO_MOVIMIENTO WHERE INT_TIPO_MOVIMIENTO=' + @CHR_CODIGO)

IF(@CHR_ENTIDAD_UTIL = 'TS')
EXEC('SELECT INT_TIPO_SERVICIO CHR_UTIL, VCH_NOMBRE FROM TA_TIPO_SERVICIO WHERE INT_TIPO_SERVICIO=' + @CHR_CODIGO)

IF(@CHR_ENTIDAD_UTIL = 'TT')
EXEC('SELECT INT_TIPO_TRANSPORTE CHR_UTIL, VCH_NOMBRE FROM TA_TIPO_SERVICIO WHERE INT_TIPO_TRANSPORTE=' + @CHR_CODIGO)

END
GO
/****** Object:  StoredProcedure [dbo].[SP_BUSCACLIENTEXDNI]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_BUSCACLIENTEXDNI]
(@VCH_DOCUMENTO AS VARCHAR(15))
AS
BEGIN
EXEC('SELECT VCH_DOCUMENTO,VCH_NOMBRES,VCH_APELLIDOS,VCH_DIRECCION,VCH_CORREO,VCH_RUTA_FOTO,VCH_TELEFONO,INT_UBIGEO
FROM TA_CLIENTE WHERE VCH_DOCUMENTO = ''' + @VCH_DOCUMENTO + '''')
END
GO
/****** Object:  StoredProcedure [dbo].[SP_ELIMINARPAGO]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_ELIMINARPAGO]
(@INT_CODIGO_CARGA AS INT)
AS
BEGIN
DELETE FROM TA_PAGO WHERE INT_CODIGO_CARGA = @INT_CODIGO_CARGA
END
GO
/****** Object:  StoredProcedure [dbo].[SP_ACTUALIZARPAGO]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_ACTUALIZARPAGO]
(@CHR_ESTADO AS CHAR(2),
@INT_CODIGO_CARGA AS INT)
AS 
BEGIN
UPDATE TA_PAGO SET CHR_ESTADO = @CHR_ESTADO WHERE INT_CODIGO_CARGA = @INT_CODIGO_CARGA
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INSERTARPAGO]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_INSERTARPAGO]
(@CHR_ESTADO AS CHAR(2),
@INT_CODIGO_CARGA AS INT,
@DBL_MONTO AS DECIMAL(15,4))
AS 
BEGIN
INSERT INTO TA_PAGO VALUES (@DBL_MONTO, GETDATE(), @CHR_ESTADO, @INT_CODIGO_CARGA)
END
GO
/****** Object:  Table [dbo].[TA_ROL]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_ROL](
	[INT_CODIGO_ROL] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [varchar](50) NULL,
 CONSTRAINT [PK_TA_ROL] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_ROL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_REFRIGERIO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_REFRIGERIO](
	[INT_CODIGO_REFRIGERIO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_DESCRIPCION] [varchar](80) NOT NULL,
	[VCH_TIPO_UNIDAD] [varchar](60) NOT NULL,
 CONSTRAINT [PK_REFRIGERIO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_REFRIGERIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_SOLICITUDES]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_SOLICITUDES](
	[INT_CODIGOSOLICITUD] [int] IDENTITY(1,1) NOT NULL,
	[BLN_ARCHIVADA] [bit] NOT NULL,
	[DTE_FECHAREGISTRO] [datetime] NOT NULL,
	[DTE_FECHARESOLUCION] [datetime] NULL,
	[VCH_ESTADO] [int] NOT NULL,
	[VCH_OBSERVACIONES] [nvarchar](max) NULL,
	[VCH_DETALLESRESOLUCION] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.TA_SOLICITUDES] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOSOLICITUD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_PRODUCTO_CABINA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_PRODUCTO_CABINA](
	[INT_CODIGO_PRODUCTOCABINA] [int] IDENTITY(1,1) NOT NULL,
	[VCH_DESCRIPCION] [varchar](100) NOT NULL,
	[VCH_TIPO_UNIDAD] [varchar](60) NOT NULL,
	[DTE_FECHA_VENCIMIENTO] [smalldatetime] NOT NULL,
 CONSTRAINT [PK_PRODUCTO_CABINA] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_PRODUCTOCABINA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_PRODUCTO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_PRODUCTO](
	[INT_CODIGO_PRODUCTO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [varchar](50) NULL,
	[VCH_DESCRIPCION] [varchar](100) NULL,
	[INT_CODIGO_CARGA] [int] NULL,
 CONSTRAINT [PK_TA_PRODUCTO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_PRODUCTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_TIPOSERVICIO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_TIPOSERVICIO](
	[INT_CODGOTIPOSERVICIO] [int] NOT NULL,
	[VCH_DETTIPOSERVICIO] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_TIPOSERVICIO] PRIMARY KEY CLUSTERED 
(
	[INT_CODGOTIPOSERVICIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_TIPOSDOCUMENTO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_TIPOSDOCUMENTO](
	[INT_CODIGOTIPODOCUMENTO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.TA_TIPOSDOCUMENTO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOTIPODOCUMENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_TIPOETIQUETA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_TIPOETIQUETA](
	[INT_CODIGOETIQUETA] [int] NOT NULL,
	[VCH_NOMBREETIQUETA] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_TIPOETIQUETA] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOETIQUETA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_TIPO_TRANSPORTE]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_TIPO_TRANSPORTE](
	[INT_TIPO_TRANSPORTE] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [varchar](100) NULL,
 CONSTRAINT [PK_TA_TIPO_TRANSPORTE] PRIMARY KEY CLUSTERED 
(
	[INT_TIPO_TRANSPORTE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_TIPO_SERVICIO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_TIPO_SERVICIO](
	[INT_CODIGOTIPOSERVICIO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [varchar](100) NULL,
 CONSTRAINT [PK_TA_TIPO_SERVICIO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOTIPOSERVICIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_TIPO_PAGO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_TIPO_PAGO](
	[INT_TIPO_PAGO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [varchar](100) NULL,
 CONSTRAINT [PK_TA_TIPO_PAGO] PRIMARY KEY CLUSTERED 
(
	[INT_TIPO_PAGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_TIPO_MOVIMIENTO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_TIPO_MOVIMIENTO](
	[INT_TIPO_MOVIMIENTO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [varchar](50) NULL,
 CONSTRAINT [PK_TA_TIPO_MOVIMIENTO] PRIMARY KEY CLUSTERED 
(
	[INT_TIPO_MOVIMIENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_TIPO_CARGA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_TIPO_CARGA](
	[INT_TIPO_CARGA] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [varchar](100) NULL,
 CONSTRAINT [PK_TA_TIPO_CARGA] PRIMARY KEY CLUSTERED 
(
	[INT_TIPO_CARGA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_UBIGEO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_UBIGEO](
	[INT_CODIGO_UBIGEO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [varchar](50) NULL,
	[VCH_CODIGO_DEPARTAMENTO] [varchar](10) NULL,
	[VCH_CODIGO_PROVINCIA] [varchar](50) NULL,
	[VCH_CODIGO_DISTRITO] [varchar](50) NULL,
 CONSTRAINT [PK_TA_UBIGEO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_UBIGEO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_VEHICULO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_VEHICULO](
	[INT_VEHICULO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_PLACA] [varchar](15) NULL,
	[VCH_MARCA] [varchar](50) NULL,
	[VCH_MODELO] [varchar](50) NULL,
	[VCH_COLOR] [varchar](50) NULL,
	[INT_TIPO_TRANSPORTE] [int] NULL,
 CONSTRAINT [PK_TA_VEHICULO] PRIMARY KEY CLUSTERED 
(
	[INT_VEHICULO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_USUARIO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_USUARIO](
	[INT_CODIGO_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[VCH_USUARIO] [varchar](50) NULL,
	[VCH_CLAVE] [varchar](50) NULL,
	[INT_CODIGO_ROL] [int] NULL,
	[INT_CODIGO_UBIGEO] [int] NULL,
	[VCH_NOMBRES] [varchar](50) NULL,
 CONSTRAINT [PK_TA_USUARIO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_USUARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_EDUCACIONES]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_EDUCACIONES](
	[INT_CODIGODETALLEHOJAVIDA] [int] NOT NULL,
	[VCH_TIPO] [nvarchar](max) NOT NULL,
	[VCH_GRADOOBTENIDO] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_dbo.TA_EDUCACIONES] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGODETALLEHOJAVIDA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_SOLICITUDESPERSONAL]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_SOLICITUDESPERSONAL](
	[INT_CODIGOSOLICITUD] [int] NOT NULL,
	[DTE_FECHAVENCIMIENTO] [datetime] NOT NULL,
	[VCH_ASUNTO] [nvarchar](max) NULL,
	[VCH_DESCRIPCION] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.TA_SOLICITUDESPERSONAL] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOSOLICITUD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_PERSONA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_PERSONA](
	[INT_CODIGOPERSONA] [int] NOT NULL,
	[INT_CODIGOTIPODOCUMENTO] [int] NULL,
	[VCH_NUMERODOCUMENTO] [varchar](15) NULL,
	[VCH_APEPATPERSONA] [varchar](30) NOT NULL,
	[VCH_APEMATPERSONA] [varchar](30) NOT NULL,
	[VCH_NOMBREPERSONA] [varchar](30) NOT NULL,
	[DTE_FECHANACIMIENTO] [smalldatetime] NULL,
	[VCH_FOTO] [nchar](10) NULL,
	[VCH_DIRECCION] [varchar](50) NULL,
	[VCH_TELEFONO] [varchar](20) NULL,
	[CHR_SEXOPERSONA] [char](1) NOT NULL,
	[INT_CODIGOCARGO] [int] NULL,
	[INT_CODIGO_UBIGEO] [int] NULL,
	[BLN_ACTIVO] [bit] NOT NULL,
 CONSTRAINT [PK_PERSONA] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOPERSONA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  StoredProcedure [dbo].[SP_ELIMINARPRODUCTOXCARGA]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_ELIMINARPRODUCTOXCARGA]
(@INT_CODIGO_CARGA AS INT)
AS 
BEGIN
DELETE FROM TA_PRODUCTO WHERE INT_CODIGO_CARGA=@INT_CODIGO_CARGA
END
GO
/****** Object:  StoredProcedure [dbo].[SP_ELIMINARPRODUCTO]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_ELIMINARPRODUCTO]
(@INT_CODIGO_PRODUCTO AS INT)
AS
BEGIN
DELETE FROM TA_PRODUCTO WHERE INT_CODIGO_PRODUCTO = @INT_CODIGO_PRODUCTO
END
GO
/****** Object:  StoredProcedure [dbo].[SP_LISTAPRODUCTOXCARGA]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LISTAPRODUCTOXCARGA]
(@INT_CODIGO_CARGA AS INT)
AS
BEGIN
SELECT INT_CODIGO_PRODUCTO,VCH_NOMBRE,VCH_DESCRIPCION,INT_CODIGO_CARGA FROM TA_PRODUCTO WHERE INT_CODIGO_CARGA=@INT_CODIGO_CARGA
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INSERTARPRODUCTO]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_INSERTARPRODUCTO]
(@INT_CODIGO_CARGA AS INT,
@VCH_NOMBRE AS VARCHAR(50),
@VCH_DESCRIPCION AS VARCHAR(200))
AS
BEGIN
INSERT INTO TA_PRODUCTO (VCH_NOMBRE,VCH_DESCRIPCION,INT_CODIGO_CARGA) 
VALUES (@VCH_NOMBRE, @VCH_DESCRIPCION, @INT_CODIGO_CARGA)
END
GO
/****** Object:  Table [dbo].[TA_AGENCIA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_AGENCIA](
	[INT_CODIGO_AGENCIA] [int] IDENTITY(1,1) NOT NULL,
	[VCH_NOMBRE] [varchar](100) NULL,
	[VCH_DIRECCION] [varchar](100) NULL,
	[INT_UBIGEO_DIRECCION] [int] NULL,
 CONSTRAINT [PK_TA_AGENCIA] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_AGENCIA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_DETALLEGUIAREMISION]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_DETALLEGUIAREMISION](
	[INT_CODIGO_GUIA] [int] NOT NULL,
	[INT_CODIGO_PRODUCTO] [int] NOT NULL,
	[VCH_DESCRIPCION] [varchar](50) NULL,
	[INT_TIPO_CARGA] [int] NULL,
	[INT_CANTIDAD] [int] NULL,
 CONSTRAINT [PK_TA_DETALLEGUIAREMISION] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_GUIA] ASC,
	[INT_CODIGO_PRODUCTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_CLIENTE]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_CLIENTE](
	[VCH_DOCUMENTO] [varchar](15) NOT NULL,
	[VCH_NOMBRES] [varchar](100) NULL,
	[VCH_APELLIDOS] [varchar](100) NULL,
	[VCH_DIRECCION] [varchar](100) NULL,
	[VCH_CORREO] [varchar](100) NULL,
	[VCH_TELEFONO] [varchar](50) NULL,
	[INT_UBIGEO] [int] NULL,
 CONSTRAINT [PK_TA_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[VCH_DOCUMENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_EXPERIENCIASLABORAL]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_EXPERIENCIASLABORAL](
	[INT_CODIGODETALLEHOJAVIDA] [int] NOT NULL,
	[VCH_CARGO] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_dbo.TA_EXPERIENCIASLABORALES] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGODETALLEHOJAVIDA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_EVALUACION_DESEMPENO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_EVALUACION_DESEMPENO](
	[INT_CODIGOEVALUACIONDESEMPENO] [int] NOT NULL,
	[DTM_FECHA] [date] NULL,
	[INT_NOTA] [int] NULL,
	[VCH_OBSERVACIONES] [varchar](250) NULL,
	[INT_CODIGOPERSONA] [int] NOT NULL,
	[INT_CODIGOEVALUADO] [int] NOT NULL,
 CONSTRAINT [PK_TA_EVALUACION_DESEMPENO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOEVALUACIONDESEMPENO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_ASIENTOVEHICULO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TA_ASIENTOVEHICULO](
	[INT_VEHICULO] [int] NOT NULL,
	[DTE_FECHASALIDA] [smalldatetime] NOT NULL,
	[DTE_HORASALIDA] [smalldatetime] NOT NULL,
	[CHR_ASIENTO] [char](2) NOT NULL,
	[INT_CODIGOESTASIENTO] [int] NOT NULL,
 CONSTRAINT [PK_ASIENTOVEHICULO] PRIMARY KEY CLUSTERED 
(
	[INT_VEHICULO] ASC,
	[DTE_FECHASALIDA] ASC,
	[DTE_HORASALIDA] ASC,
	[CHR_ASIENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_ALMACEN]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_ALMACEN](
	[INT_CODIGO_ALMACEN] [int] IDENTITY(1,1) NOT NULL,
	[INT_CODIGO_AGENCIA] [int] NULL,
	[VCH_NOMBRE] [varchar](50) NULL,
	[VCH_DESCRIPCION] [varchar](100) NULL,
	[INT_CAPACIDAD] [int] NULL,
	[VCH_DIRECCION] [varchar](100) NULL,
 CONSTRAINT [PK_TA_ALMACEN] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_ALMACEN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  StoredProcedure [dbo].[SP_VALIDAUSUARIO]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_VALIDAUSUARIO]    
(@VCH_USUARIO AS VARCHAR(50),    
@VCH_CLAVE AS VARCHAR(50))    
AS    
BEGIN    
SELECT U.INT_CODIGO_USUARIO,U.VCH_USUARIO,U.VCH_CLAVE,U.INT_CODIGO_ROL,U.VCH_NOMBRES,R.VCH_NOMBRE ROL,U.INT_CODIGO_UBIGEO, UB.VCH_NOMBRE NOM_DEPARTAMENTO
FROM TA_USUARIO U     
INNER JOIN TA_ROL R ON U.INT_CODIGO_ROL = R.INT_CODIGO_ROL    
INNER JOIN TA_UBIGEO UB ON U.INT_CODIGO_UBIGEO = UB.INT_CODIGO_UBIGEO
WHERE U.VCH_USUARIO = @VCH_USUARIO AND U.VCH_CLAVE = @VCH_CLAVE    
END 


SELECT * FROM TA_UBIGEO
GO
/****** Object:  Table [dbo].[TA_PASAJERO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_PASAJERO](
	[INT_CODIGOPASAJERO] [int] NOT NULL,
	[INT_CODIGOPERSONA] [int] NOT NULL,
	[INT_EDADPASAJERO] [int] NULL,
	[BLN_ACTIVO] [bit] NOT NULL,
 CONSTRAINT [PK_TA_PASAJERO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOPASAJERO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_RUTA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_RUTA](
	[INT_CODIGO_RUTA] [int] IDENTITY(1,1) NOT NULL,
	[VCH_ORIGEN] [varchar](30) NULL,
	[VCH_DESTINO] [varchar](30) NULL,
	[INT_CODIGO_AGENCIAORIGEN] [int] NULL,
	[INT_CODIGO_AGENCIADESTINO] [int] NULL,
	[BLN_ESTADO] [bit] NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_RUTA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_SOLICITUDESCAPACITACION]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_SOLICITUDESCAPACITACION](
	[INT_CODIGOSOLICITUD] [int] NOT NULL,
	[DTE_FECHAPLANIFICADA] [datetime] NOT NULL,
	[INT_CODIGOPERSONA] [int] NOT NULL,
	[VCH_ESPECIALIDAD] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_dbo.TA_SOLICITUDESCAPACITACION] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOSOLICITUD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_STOCK]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_STOCK](
	[INT_CODIGO_PRODUCTOCABINA] [int] NOT NULL,
	[INT_CODIGO_ALMACEN] [int] NOT NULL,
	[INT_CANTIDAD_INICIAL] [int] NOT NULL,
	[INT_STOCK_MINIMO] [int] NOT NULL,
 CONSTRAINT [PK_STOCK] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_PRODUCTOCABINA] ASC,
	[INT_CODIGO_ALMACEN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_PROGRAMACION_RUTA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_PROGRAMACION_RUTA](
	[INT_CODIGO_PROGRAMACION_RUTA] [int] IDENTITY(1,1) NOT NULL,
	[INT_CODIGO_RUTA] [int] NULL,
	[DTM_FECHA_ORIGEN] [datetime] NULL,
	[DTM_FECHA_DESTINO] [datetime] NULL,
	[TIM_HORA_SALIDA] [time](7) NULL,
	[TIM_HORA_LLEGADA] [time](7) NULL,
	[INT_TIPO_SERVICIO] [int] NULL,
	[INT_CODIGOVEHICULO] [int] NULL,
	[INT_CODIGOPERSONA] [int] NULL,
	[BLN_ESTADO] [bit] NULL,
 CONSTRAINT [PK_TA_PROGRAMACION_RUTA] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_PROGRAMACION_RUTA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[SP_ASIENTOSVEHICULO]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[SP_ASIENTOSVEHICULO]
(
   @pCodVehiculo Int = 0
)
As
Begin
   Set Nocount On
   Select 
      a.INT_VEHICULO,
      FechaSalida = Convert(varchar(20),a.DTE_FECHASALIDA,103),
      HoraSalida  = RIGHT(Convert(datetime,a.DTE_HORASALIDA,108),8),
      a.CHR_ASIENTO,
      b.VCH_PLACA,
      c.VCH_DETESTASIENTO
   From TA_ASIENTOVEHICULO a 
   Inner Join TA_VEHICULO        b On a.INT_VEHICULO     = b.INT_VEHICULO
   Inner Join TA_ESTADOASIENTO   c On a.INT_CODIGOESTASIENTO   = c.INT_CODIGOESTASIENTO
   Where a.INT_CODIGOESTASIENTO = 3 And a.INT_VEHICULO = @pCodVehiculo
   Set Nocount Off
End
GO
/****** Object:  Table [dbo].[TA_CARGA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_CARGA](
	[INT_CODIGO_CARGA] [int] NOT NULL,
	[VCH_FICHA] [varchar](20) NULL,
	[DTM_FECHA_REGISTRO] [datetime] NULL,
	[VCH_REMITENTE] [varchar](50) NULL,
	[VCH_DESTINATARIO] [varchar](50) NULL,
	[DBL_PESOTOTAL] [decimal](8, 2) NULL,
	[DBL_IMPORTETOTAL] [decimal](8, 2) NULL,
	[VCH_OBSERVACION] [varchar](255) NULL,
	[VCH_CLAVE_SEGURIDAD] [varchar](10) NULL,
	[INT_TIPO_PAGO] [int] NULL,
	[INT_CODIGO_PROGRAMACION_RUTA] [int] NULL,
	[VCH_CLIENTE_ORIGEN] [varchar](15) NULL,
	[VCH_ESTADOPAGO] [varchar](20) NULL,
	[INT_CODIGO_GUIA] [int] NULL,
	[VCH_CLIENTE_DESTINO] [varchar](15) NULL,
	[VCH_ESTADO] [varchar](25) NULL,
 CONSTRAINT [PK_TA_CARGA_1] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_CARGA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_BOLETO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_BOLETO](
	[INT_CODIGOBOLETO] [int] NOT NULL,
	[INT_CODIGO_PROGRAMACION_RUTA] [int] NULL,
	[INT_CODIGOPASAJERO] [int] NOT NULL,
	[CHR_NUMEROBOLETO] [char](10) NOT NULL,
	[DEC_PRECIOPASAJE] [decimal](12, 2) NOT NULL,
	[DTE_FECHACHECKIN] [smalldatetime] NULL,
	[DTE_FECHASALIDA] [smalldatetime] NOT NULL,
	[DTE_HORASALIDA] [smalldatetime] NOT NULL,
	[CHR_ASIENTO] [char](2) NULL,
	[VCH_UBICACION] [varchar](60) NULL,
	[BLN_ACTIVO] [bit] NOT NULL,
 CONSTRAINT [PK_TA_BOLETO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGOBOLETO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_SOLICITUDCOCINA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_SOLICITUDCOCINA](
	[INT_CODIGO_SOLICITUDCOCINA] [int] IDENTITY(1,1) NOT NULL,
	[INT_CODIGO_REFRIGERIO] [int] NOT NULL,
	[INT_CODIGO_PROGRAMACION_RUTA] [int] NOT NULL,
	[INT_CANTIDAD] [int] NULL,
	[DTE_FECHA_SOLICITUD] [smalldatetime] NULL,
	[BLN_ESTADO] [bit] NOT NULL,
 CONSTRAINT [PK_SOLPRODCOCINA] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_SOLICITUDCOCINA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_SOLPRODUCTODECABINA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_SOLPRODUCTODECABINA](
	[INT_CODIGO_SOLPRODUCTODECABINA] [int] IDENTITY(1,1) NOT NULL,
	[DTE_FECHA_SOLICITUD] [smalldatetime] NOT NULL,
	[INT_CODIGO_PRODUCTOCABINA] [int] NOT NULL,
	[INT_CODIGO_PROGRAMACION_RUTA] [int] NOT NULL,
	[INT_CANTIDAD] [int] NOT NULL,
	[BLN_ESTADO] [bit] NOT NULL,
 CONSTRAINT [PK_SOLPRODUCTODECABINA] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_SOLPRODUCTODECABINA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_TRAZABILIDADCARGA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_TRAZABILIDADCARGA](
	[INT_CODIGO_CARGA] [int] NOT NULL,
	[VCH_OBSERVACIONES] [varchar](100) NULL,
	[VCH_ESTADOCARGA] [varchar](50) NOT NULL,
	[DTM_FECHA_REGISTRO] [datetime] NULL,
 CONSTRAINT [PK_TA_TRAZABILIDADCARGA_1] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_CARGA] ASC,
	[VCH_ESTADOCARGA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_SOLICITUDINSUMO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_SOLICITUDINSUMO](
	[INT_CODIGO_SOLICITUDINSUMO] [int] IDENTITY(1,1) NOT NULL,
	[INT_CODIGO_SOLICITUDCOCINA] [int] NOT NULL,
	[INT_CODIGO_INSUMO] [int] NOT NULL,
	[DTE_FECHA_SOLICITUD] [smalldatetime] NOT NULL,
	[INT_CANTIDAD] [int] NULL,
	[VCH_UNIDAD] [nvarchar](10) NOT NULL,
	[BLN_ESTADO] [bit] NOT NULL,
 CONSTRAINT [PK_SOLICITUDINSUMO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_SOLICITUDINSUMO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TA_FICHA_MOVIMIENTO]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_FICHA_MOVIMIENTO](
	[INT_CODIGO_MOVIMIENTO] [int] IDENTITY(1,1) NOT NULL,
	[DTM_FECHAHORA] [datetime] NULL,
	[INT_TIPO_MOVIMIENTO] [int] NULL,
	[INT_CODIGO_ALMACEN] [int] NULL,
	[INT_CODIGO_CARGA] [int] NULL,
	[VCH_OBSERVACION] [varchar](200) NULL,
 CONSTRAINT [PK_TA_FICHA_MOVIMIENTO] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_MOVIMIENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_DETALLECARGA]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_DETALLECARGA](
	[INT_CODIGO_CARGA] [int] NOT NULL,
	[INT_CODIGO_PRODUCTO] [int] NOT NULL,
	[VCH_DESCRIPCION] [varchar](50) NULL,
	[INT_TIPO_CARGA] [int] NULL,
	[INT_CANTIDAD] [int] NULL,
	[DBL_PESO] [decimal](8, 2) NULL,
	[DBL_IMPORTE] [decimal](8, 2) NULL,
 CONSTRAINT [PK_TA_DETALLECARGA] PRIMARY KEY CLUSTERED 
(
	[INT_CODIGO_CARGA] ASC,
	[INT_CODIGO_PRODUCTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TA_EQUIPAJE]    Script Date: 09/11/2014 19:59:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TA_EQUIPAJE](
	[INT_CODEQUIPAJE] [int] NOT NULL,
	[INT_CODIGOBOLETO] [int] NULL,
	[INT_CODIGOETIQUETA] [int] NOT NULL,
	[CHR_NUMEROEQUIPAJE] [char](10) NOT NULL,
	[DTE_FECHAHORA] [smalldatetime] NOT NULL,
	[DEC_PESO] [decimal](12, 2) NULL,
	[CHR_TAMANO] [char](20) NULL,
	[DEC_PRECIO] [decimal](12, 2) NULL,
	[VCH_UBICACION] [varchar](20) NULL,
	[CHR_CODIGOBARRAS] [char](20) NULL,
	[VCH_ESTADOEQUIPAJE] [varchar](20) NOT NULL,
	[BLN_ACTIVO] [bit] NOT NULL,
 CONSTRAINT [PK_EQUIPAJE] PRIMARY KEY CLUSTERED 
(
	[INT_CODEQUIPAJE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  StoredProcedure [dbo].[SP_BOLETOACTUALIZARASIENTO]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[SP_BOLETOACTUALIZARASIENTO]
(
   @CHR_NUMEROBOLETO Char(10) = Null,
   @CHR_ASIENTO Char(2) = Null
)
As
Begin
   Set Nocount On
   

   -- ISSAC
   /*
Update TA_BOLETO Set DTE_FECHACHECKIN = GETDATE() Where CHR_NUMEROBOLETO=@pNROBOLETO
Update g
Set g.INT_CODIGOESTASIENTO = 1 -- Ocupado
From TA_BOLETO (Nolock) a
Inner Join TA_ASIENTOVEHICULO g On a.INT_VEHICULO = g.INT_VEHICULO And a.DTE_FECHASALIDA=g.DTE_FECHASALIDA And a.DTE_HORASALIDA=g.DTE_HORASALIDA And a.CHR_ASIENTO=g.CHR_ASIENTO
Where a.CHR_NUMEROBOLETO = @pNROBOLETO
exec SP_BOLETOCONSULTAR @pNROBOLETO,Null
   */
   
      Update TA_BOLETO Set CHR_ASIENTO = @CHR_ASIENTO Where CHR_NUMEROBOLETO=@CHR_NUMEROBOLETO
   
   UPDATE av
   SET av.INT_CODIGOESTASIENTO = 2 -- Seleccionado
   FROM TA_BOLETO bo
   INNER JOIN TA_PROGRAMACION_RUTA pr ON bo.INT_CODIGO_PROGRAMACION_RUTA = bo.INT_CODIGO_PROGRAMACION_RUTA
   INNER JOIN TA_VEHICULO ve ON pr.INT_CODIGOVEHICULO = ve.INT_VEHICULO 
   INNER JOIN TA_ASIENTOVEHICULO av ON ve.INT_VEHICULO = av.INT_VEHICULO AND bo.DTE_FECHASALIDA = av.DTE_FECHASALIDA AND bo.DTE_HORASALIDA = av.DTE_HORASALIDA AND bo.CHR_ASIENTO = av.CHR_ASIENTO
   WHERE bo.CHR_NUMEROBOLETO = @CHR_NUMEROBOLETO
   
   Set Nocount Off
End
GO
/****** Object:  StoredProcedure [dbo].[SP_ELIMINARCARGA]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_ELIMINARCARGA]
(@INT_CODIGO_CARGA AS INT)
AS
BEGIN
DELETE FROM TA_CARGA  WHERE INT_CODIGO_CARGA=@INT_CODIGO_CARGA
END
GO
/****** Object:  StoredProcedure [dbo].[SP_BOLETOCONSULTAR]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[SP_BOLETOCONSULTAR]
(
   @pNROBOLETO Char(10) = Null,
   @pDNI       Char(8)  = Null
)
As
Begin
   Set Nocount On
   If(Len(@pNROBOLETO)>0 Or Len(@pDNI)>0) 
   Begin
   If(@pNROBOLETO='') Set @pNROBOLETO = Null
   If(@pDNI='') Set @pDNI = Null   
   End

   SELECT 
bo.CHR_NUMEROBOLETO,
Pasajero = pe.VCH_APEPATPERSONA +' '+ pe.VCH_APEMATPERSONA +', '+ pe.VCH_NOMBREPERSONA,
bo.DEC_PRECIOPASAJE,
ve.VCH_PLACA,
ts.VCH_NOMBRE,
ru.VCH_ORIGEN,
ru.VCH_DESTINO,
FechaSalida = Convert(varchar(20),bo.DTE_FECHASALIDA,103),
HoraSalida  = RIGHT(Convert(datetime,bo.DTE_HORASALIDA,108),8),
bo.CHR_ASIENTO,
bo.VCH_UBICACION,
Chofer = co.VCH_APEPATPERSONA +' '+ co.VCH_APEMATPERSONA +', '+ co.VCH_NOMBREPERSONA,
eav.VCH_DETESTASIENTO,
FechaActual = Convert(varchar(20),GETDATE(),103),
HoraActual  = RIGHT(Convert(datetime, GETDATE(), 108),8)
FROM TA_BOLETO (Nolock) bo
INNER JOIN TA_PASAJERO pa ON bo.INT_CODIGOPASAJERO = pa.INT_CODIGOPASAJERO 
INNER JOIN TA_PERSONA pe ON pa.INT_CODIGOPERSONA = pe.INT_CODIGOPERSONA
INNER JOIN TA_PROGRAMACION_RUTA pr On bo.INT_CODIGO_PROGRAMACION_RUTA = pr.INT_CODIGO_PROGRAMACION_RUTA
INNER JOIN TA_PERSONA co ON pr.INT_CODIGOPERSONA = co.INT_CODIGOPERSONA AND co.INT_CODIGOCARGO = 2
INNER JOIN TA_RUTA ru ON pr.INT_CODIGO_RUTA = ru.INT_CODIGO_RUTA
INNER JOIN TA_VEHICULO ve ON pr.INT_CODIGOVEHICULO = ve.INT_VEHICULO
INNER JOIN TA_TIPO_SERVICIO ts ON pr.INT_TIPO_SERVICIO = ts.INT_CODIGOTIPOSERVICIO 
INNER JOIN TA_ASIENTOVEHICULO av ON pr.INT_CODIGOVEHICULO = av.INT_VEHICULO And bo.DTE_FECHASALIDA = av.DTE_FECHASALIDA And bo.DTE_HORASALIDA = av.DTE_HORASALIDA And bo.CHR_ASIENTO = av.CHR_ASIENTO
INNER JOIN TA_ESTADOASIENTO eav ON av.INT_CODIGOESTASIENTO = eav.INT_CODIGOESTASIENTO
WHERE av.INT_CODIGOESTASIENTO <> 3
AND bo.CHR_NUMEROBOLETO = COALESCE(@pNROBOLETO,bo.CHR_NUMEROBOLETO)
AND pe.VCH_NUMERODOCUMENTO = COALESCE(@pDNI,pe.VCH_NUMERODOCUMENTO)
Set Nocount Off
   
   
End
GO
/****** Object:  StoredProcedure [dbo].[SP_TIKETCONSULTAR]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[SP_TIKETCONSULTAR]
As
Begin
   Set Nocount On
   Select 
      a.INT_CODEQUIPAJE,
      a.CHR_NUMEROEQUIPAJE,
      a.DTE_FECHAHORA,
      a.DEC_PESO,
      a.CHR_TAMANO,
      a.CHR_CODIGOBARRAS,
      a.VCH_ESTADOEQUIPAJE,
      b.VCH_NOMBREETIQUETA
   from TA_EQUIPAJE a 
   Inner Join TA_TIPOETIQUETA b On a.INT_CODIGOETIQUETA = b.INT_CODIGOETIQUETA
   Where a.INT_CODIGOBOLETO Is Null
   And a.BLN_ACTIVO=1
   
   Set Nocount Off
End
GO
/****** Object:  StoredProcedure [dbo].[SP_BOLETOCHECKIN]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[SP_BOLETOCHECKIN]
(
   @pNROBOLETO Char(10) = Null
)
As
Begin
   Set Nocount On
   Update TA_BOLETO Set DTE_FECHACHECKIN = GETDATE() Where CHR_NUMEROBOLETO=@pNROBOLETO
    
   UPDATE av
   SET av.INT_CODIGOESTASIENTO = 1
   --SELECT bo.*
   FROM TA_BOLETO bo
   INNER JOIN TA_PROGRAMACION_RUTA pr ON bo.INT_CODIGO_PROGRAMACION_RUTA = bo.INT_CODIGO_PROGRAMACION_RUTA
   INNER JOIN TA_VEHICULO ve ON pr.INT_CODIGOVEHICULO = ve.INT_VEHICULO 
   INNER JOIN TA_ASIENTOVEHICULO av ON ve.INT_VEHICULO = av.INT_VEHICULO AND bo.DTE_FECHASALIDA = av.DTE_FECHASALIDA AND bo.DTE_HORASALIDA = av.DTE_HORASALIDA AND bo.CHR_ASIENTO = av.CHR_ASIENTO
   WHERE bo.CHR_NUMEROBOLETO = @pNROBOLETO
   
   -- ISSAC
   /*
   Update TA_BOLETO Set DTE_FECHACHECKIN = GETDATE() Where CHR_NUMEROBOLETO=@pNROBOLETO
Update g
Set g.INT_CODIGOESTASIENTO = 1 -- Ocupado
From TA_BOLETO (Nolock) a
Inner Join TA_ASIENTOVEHICULO g On a.INT_VEHICULO = g.INT_VEHICULO And a.DTE_FECHASALIDA=g.DTE_FECHASALIDA And a.DTE_HORASALIDA=g.DTE_HORASALIDA And a.CHR_ASIENTO=g.CHR_ASIENTO
Where a.CHR_NUMEROBOLETO = @pNROBOLETO
exec SP_BOLETOCONSULTAR @pNROBOLETO,Null
   */
   
   
   exec  SP_BOLETOCONSULTAR @pNROBOLETO,Null
   
   Set Nocount Off
End
GO
/****** Object:  StoredProcedure [dbo].[SP_BOLETOCANCELARCHECKIN]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[SP_BOLETOCANCELARCHECKIN]
(
   @pNROBOLETO Char(10) = Null
)
As
Begin
   Set Nocount On
   
   /*
   Update g
   Set g.INT_CODIGOESTASIENTO = 3 -- Libre
   From TA_BOLETO (Nolock)       a
   Inner Join TA_ASIENTOVEHICULO g On a.INT_VEHICULO     = g.INT_VEHICULO  And a.DTE_FECHASALIDA=g.DTE_FECHASALIDA And a.DTE_HORASALIDA=g.DTE_HORASALIDA And a.CHR_ASIENTO=g.CHR_ASIENTO
   Where a.CHR_NUMEROBOLETO = @pNROBOLETO  
   */
   
   UPDATE av
   SET av.INT_CODIGOESTASIENTO = 3 -- Libre
   FROM TA_BOLETO bo
   INNER JOIN TA_PROGRAMACION_RUTA pr ON bo.INT_CODIGO_PROGRAMACION_RUTA = bo.INT_CODIGO_PROGRAMACION_RUTA
   INNER JOIN TA_VEHICULO ve ON pr.INT_CODIGOVEHICULO = ve.INT_VEHICULO 
   INNER JOIN TA_ASIENTOVEHICULO av ON ve.INT_VEHICULO = av.INT_VEHICULO AND bo.DTE_FECHASALIDA = av.DTE_FECHASALIDA AND bo.DTE_HORASALIDA = av.DTE_HORASALIDA AND bo.CHR_ASIENTO = av.CHR_ASIENTO
   WHERE bo.CHR_NUMEROBOLETO = @pNROBOLETO
   
   exec  SP_BOLETOCONSULTAR @pNROBOLETO,Null
   
   Set Nocount Off
End
GO
/****** Object:  StoredProcedure [dbo].[SP_EQUIPAJEACTUALIZAR]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[SP_EQUIPAJEACTUALIZAR]
(
   @INT_CODEQUIPAJE int,
   @INT_CODIGOBOLETO int
)
As
Begin
   Set Nocount On
   Update TA_EQUIPAJE Set INT_CODIGOBOLETO = Null,VCH_ESTADOEQUIPAJE='POR CONFIRMAR' 
   Where INT_CODIGOBOLETO = @INT_CODIGOBOLETO
   
   Update TA_EQUIPAJE Set INT_CODIGOBOLETO = @INT_CODIGOBOLETO,VCH_ESTADOEQUIPAJE='CONFIRMADO' 
   Where INT_CODEQUIPAJE = @INT_CODEQUIPAJE
   
   Set Nocount Off
End
GO
/****** Object:  StoredProcedure [dbo].[SP_EQUIPAJECONSULTAR]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[SP_EQUIPAJECONSULTAR]
(
   @pNROBOLETO Char(10) = Null,
   @pDNI       Char(8)  = Null
)
As
Begin
   Set Nocount On
   If(Len(@pNROBOLETO)>0 Or Len(@pDNI)>0) 
   Begin
   If(@pNROBOLETO='') Set @pNROBOLETO = Null
   If(@pDNI='') Set @pDNI = Null   
   End
SELECT
bo.INT_CODIGOBOLETO,
bo.CHR_NUMEROBOLETO,
Pasajero = pe.VCH_APEPATPERSONA +' '+ pe.VCH_APEMATPERSONA +', '+ pe.VCH_NOMBREPERSONA,
eq.DEC_PESO,
ru.VCH_ORIGEN,
ru.VCH_DESTINO,
FechaSalida = Convert(varchar(20),bo.DTE_FECHASALIDA,103),
HoraSalida  = RIGHT(Convert(datetime,bo.DTE_HORASALIDA,108),8),
te.VCH_NOMBREETIQUETA,
eq.VCH_UBICACION,
FechaActual = Convert(varchar(20),GETDATE(),103),
HoraActual  = RIGHT(Convert(datetime, GETDATE(), 108),8),
eq.VCH_ESTADOEQUIPAJE
FROM TA_BOLETO bo
INNER JOIN TA_PROGRAMACION_RUTA pr ON bo.INT_CODIGO_PROGRAMACION_RUTA = pr.INT_CODIGO_PROGRAMACION_RUTA
INNER JOIN TA_RUTA ru ON pr.INT_CODIGO_RUTA = ru.INT_CODIGO_RUTA 
INNER JOIN TA_PASAJERO pa ON bo.INT_CODIGOPASAJERO = pa.INT_CODIGOPASAJERO AND pa.BLN_ACTIVO = 1
INNER JOIN TA_PERSONA pe ON pa.INT_CODIGOPERSONA = pe.INT_CODIGOPERSONA AND pe.BLN_ACTIVO = 1
INNER JOIN TA_TIPO_SERVICIO ts ON pr.INT_TIPO_SERVICIO = ts.INT_CODIGOTIPOSERVICIO 
INNER JOIN TA_VEHICULO v ON pr.INT_CODIGOVEHICULO = v.INT_VEHICULO 
INNER JOIN TA_ASIENTOVEHICULO av ON v.INT_VEHICULO = av.INT_VEHICULO AND bo.DTE_FECHASALIDA = av.DTE_FECHASALIDA AND bo.DTE_HORASALIDA = av.DTE_HORASALIDA AND bo.CHR_ASIENTO = av.CHR_ASIENTO
INNER JOIN TA_ESTADOASIENTO eav ON av.INT_CODIGOESTASIENTO = eav.INT_CODIGOESTASIENTO 
INNER JOIN TA_EQUIPAJE eq ON bo.INT_CODIGOBOLETO = eq.INT_CODIGOBOLETO AND eq.BLN_ACTIVO = 1
INNER JOIN TA_TIPOETIQUETA te ON eq.INT_CODIGOETIQUETA = te.INT_CODIGOETIQUETA
WHERE av.INT_CODIGOESTASIENTO <> 3 And eq.VCH_ESTADOEQUIPAJE <> 'CANCELADO'
AND bo.CHR_NUMEROBOLETO = COALESCE(@pNROBOLETO,bo.CHR_NUMEROBOLETO)
AND pe.VCH_NUMERODOCUMENTO = COALESCE(@pDNI,pe.VCH_NUMERODOCUMENTO)
   Set Nocount Off
End
GO
/****** Object:  StoredProcedure [dbo].[SP_EQUIPAJEACTUALIZARESTADO]    Script Date: 09/11/2014 19:59:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[SP_EQUIPAJEACTUALIZARESTADO]
(
   @pNROBOLETO Char(10),
   @pAccion Int
)
As
Begin
   Set Nocount On
   Declare @Estado varchar(20)
   
   -- If (@pAccion=1) Set @Estado='POR CONFIRMAR'   
   If (@pAccion=2) 
   Begin
      Set @Estado='CONFIRMADO'
      Update a
      Set a.VCH_ESTADOEQUIPAJE = @Estado
      From TA_EQUIPAJE (Nolock)       a
      Inner Join TA_BOLETO b On a.INT_CODIGOBOLETO     = b.INT_CODIGOBOLETO And b.BLN_ACTIVO = 1
      Where b.CHR_NUMEROBOLETO = @pNROBOLETO 
   End
   If (@pAccion=3) 
   Begin 
      Set @Estado='CANCELADO'
      Update a
      Set a.VCH_ESTADOEQUIPAJE = @Estado,
          a.INT_CODIGOBOLETO   = Null
      From TA_EQUIPAJE (Nolock)       a
      Inner Join TA_BOLETO b On a.INT_CODIGOBOLETO     = b.INT_CODIGOBOLETO And b.BLN_ACTIVO = 1
      Where b.CHR_NUMEROBOLETO = @pNROBOLETO 
   End
     
   exec  SP_EQUIPAJECONSULTAR @pNROBOLETO,Null
   
   Set Nocount Off
End
GO
/****** Object:  Default [DF__TA_EQUIPA__BLN_A__6B24EA82]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_EQUIPAJE] ADD  DEFAULT ((1)) FOR [BLN_ACTIVO]
GO
/****** Object:  Default [DF__TA_PASAJE__BLN_A__6C190EBB]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_PASAJERO] ADD  DEFAULT ((1)) FOR [BLN_ACTIVO]
GO
/****** Object:  Default [DF__TA_PERSON__BLN_A__4BAC3F29]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_PERSONA] ADD  CONSTRAINT [DF__TA_PERSON__BLN_A__4BAC3F29]  DEFAULT ((1)) FOR [BLN_ACTIVO]
GO
/****** Object:  ForeignKey [FK_TA_AGENCIA_TA_UBIGEO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_AGENCIA]  WITH CHECK ADD  CONSTRAINT [FK_TA_AGENCIA_TA_UBIGEO] FOREIGN KEY([INT_UBIGEO_DIRECCION])
REFERENCES [dbo].[TA_UBIGEO] ([INT_CODIGO_UBIGEO])
GO
ALTER TABLE [dbo].[TA_AGENCIA] CHECK CONSTRAINT [FK_TA_AGENCIA_TA_UBIGEO]
GO
/****** Object:  ForeignKey [FK_TA_ALMACEN_TA_AGENCIA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_ALMACEN]  WITH CHECK ADD  CONSTRAINT [FK_TA_ALMACEN_TA_AGENCIA] FOREIGN KEY([INT_CODIGO_AGENCIA])
REFERENCES [dbo].[TA_AGENCIA] ([INT_CODIGO_AGENCIA])
GO
ALTER TABLE [dbo].[TA_ALMACEN] CHECK CONSTRAINT [FK_TA_ALMACEN_TA_AGENCIA]
GO
/****** Object:  ForeignKey [FK_TA_ASIEN_REFERENCE_TA_ESTAD]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_ASIENTOVEHICULO]  WITH CHECK ADD  CONSTRAINT [FK_TA_ASIEN_REFERENCE_TA_ESTAD] FOREIGN KEY([INT_CODIGOESTASIENTO])
REFERENCES [dbo].[TA_ESTADOASIENTO] ([INT_CODIGOESTASIENTO])
GO
ALTER TABLE [dbo].[TA_ASIENTOVEHICULO] CHECK CONSTRAINT [FK_TA_ASIEN_REFERENCE_TA_ESTAD]
GO
/****** Object:  ForeignKey [FK_TA_ASIEN_REFERENCE_TA_VEHIC]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_ASIENTOVEHICULO]  WITH CHECK ADD  CONSTRAINT [FK_TA_ASIEN_REFERENCE_TA_VEHIC] FOREIGN KEY([INT_VEHICULO])
REFERENCES [dbo].[TA_VEHICULO] ([INT_VEHICULO])
GO
ALTER TABLE [dbo].[TA_ASIENTOVEHICULO] CHECK CONSTRAINT [FK_TA_ASIEN_REFERENCE_TA_VEHIC]
GO
/****** Object:  ForeignKey [FK_TA_BOLETO_TA_PASAJERO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_BOLETO]  WITH CHECK ADD  CONSTRAINT [FK_TA_BOLETO_TA_PASAJERO] FOREIGN KEY([INT_CODIGOPASAJERO])
REFERENCES [dbo].[TA_PASAJERO] ([INT_CODIGOPASAJERO])
GO
ALTER TABLE [dbo].[TA_BOLETO] CHECK CONSTRAINT [FK_TA_BOLETO_TA_PASAJERO]
GO
/****** Object:  ForeignKey [FK_TA_BOLETO_TA_PROGRAMACION_RUTA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_BOLETO]  WITH CHECK ADD  CONSTRAINT [FK_TA_BOLETO_TA_PROGRAMACION_RUTA] FOREIGN KEY([INT_CODIGO_PROGRAMACION_RUTA])
REFERENCES [dbo].[TA_PROGRAMACION_RUTA] ([INT_CODIGO_PROGRAMACION_RUTA])
GO
ALTER TABLE [dbo].[TA_BOLETO] CHECK CONSTRAINT [FK_TA_BOLETO_TA_PROGRAMACION_RUTA]
GO
/****** Object:  ForeignKey [FK_TA_CARGA_TA_CLIENTE]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_CARGA]  WITH CHECK ADD  CONSTRAINT [FK_TA_CARGA_TA_CLIENTE] FOREIGN KEY([VCH_CLIENTE_ORIGEN])
REFERENCES [dbo].[TA_CLIENTE] ([VCH_DOCUMENTO])
GO
ALTER TABLE [dbo].[TA_CARGA] CHECK CONSTRAINT [FK_TA_CARGA_TA_CLIENTE]
GO
/****** Object:  ForeignKey [FK_TA_CARGA_TA_CLIENTE1]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_CARGA]  WITH CHECK ADD  CONSTRAINT [FK_TA_CARGA_TA_CLIENTE1] FOREIGN KEY([VCH_CLIENTE_DESTINO])
REFERENCES [dbo].[TA_CLIENTE] ([VCH_DOCUMENTO])
GO
ALTER TABLE [dbo].[TA_CARGA] CHECK CONSTRAINT [FK_TA_CARGA_TA_CLIENTE1]
GO
/****** Object:  ForeignKey [FK_TA_CARGA_TA_GUIAREMISION]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_CARGA]  WITH CHECK ADD  CONSTRAINT [FK_TA_CARGA_TA_GUIAREMISION] FOREIGN KEY([INT_CODIGO_GUIA])
REFERENCES [dbo].[TA_GUIAREMISION] ([INT_CODIGO_GUIA])
GO
ALTER TABLE [dbo].[TA_CARGA] CHECK CONSTRAINT [FK_TA_CARGA_TA_GUIAREMISION]
GO
/****** Object:  ForeignKey [FK_TA_CARGA_TA_PROGRAMACION_RUTA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_CARGA]  WITH CHECK ADD  CONSTRAINT [FK_TA_CARGA_TA_PROGRAMACION_RUTA] FOREIGN KEY([INT_CODIGO_PROGRAMACION_RUTA])
REFERENCES [dbo].[TA_PROGRAMACION_RUTA] ([INT_CODIGO_PROGRAMACION_RUTA])
GO
ALTER TABLE [dbo].[TA_CARGA] CHECK CONSTRAINT [FK_TA_CARGA_TA_PROGRAMACION_RUTA]
GO
/****** Object:  ForeignKey [FK_TA_CARGA_TA_TIPO_PAGO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_CARGA]  WITH CHECK ADD  CONSTRAINT [FK_TA_CARGA_TA_TIPO_PAGO] FOREIGN KEY([INT_TIPO_PAGO])
REFERENCES [dbo].[TA_TIPO_PAGO] ([INT_TIPO_PAGO])
GO
ALTER TABLE [dbo].[TA_CARGA] CHECK CONSTRAINT [FK_TA_CARGA_TA_TIPO_PAGO]
GO
/****** Object:  ForeignKey [FK_TA_CLIENTE_TA_UBIGEO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_TA_CLIENTE_TA_UBIGEO] FOREIGN KEY([INT_UBIGEO])
REFERENCES [dbo].[TA_UBIGEO] ([INT_CODIGO_UBIGEO])
GO
ALTER TABLE [dbo].[TA_CLIENTE] CHECK CONSTRAINT [FK_TA_CLIENTE_TA_UBIGEO]
GO
/****** Object:  ForeignKey [FK_TA_DETALLECARGA_TA_CARGA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_DETALLECARGA]  WITH CHECK ADD  CONSTRAINT [FK_TA_DETALLECARGA_TA_CARGA] FOREIGN KEY([INT_CODIGO_CARGA])
REFERENCES [dbo].[TA_CARGA] ([INT_CODIGO_CARGA])
GO
ALTER TABLE [dbo].[TA_DETALLECARGA] CHECK CONSTRAINT [FK_TA_DETALLECARGA_TA_CARGA]
GO
/****** Object:  ForeignKey [FK_TA_DETALLECARGA_TA_PRODUCTO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_DETALLECARGA]  WITH CHECK ADD  CONSTRAINT [FK_TA_DETALLECARGA_TA_PRODUCTO] FOREIGN KEY([INT_CODIGO_CARGA])
REFERENCES [dbo].[TA_PRODUCTO] ([INT_CODIGO_PRODUCTO])
GO
ALTER TABLE [dbo].[TA_DETALLECARGA] CHECK CONSTRAINT [FK_TA_DETALLECARGA_TA_PRODUCTO]
GO
/****** Object:  ForeignKey [FK_TA_DETALLECARGA_TA_TIPO_CARGA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_DETALLECARGA]  WITH CHECK ADD  CONSTRAINT [FK_TA_DETALLECARGA_TA_TIPO_CARGA] FOREIGN KEY([INT_TIPO_CARGA])
REFERENCES [dbo].[TA_TIPO_CARGA] ([INT_TIPO_CARGA])
GO
ALTER TABLE [dbo].[TA_DETALLECARGA] CHECK CONSTRAINT [FK_TA_DETALLECARGA_TA_TIPO_CARGA]
GO
/****** Object:  ForeignKey [FK_TA_DETALLEGUIAREMISION_TA_GUIAREMISION]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_DETALLEGUIAREMISION]  WITH CHECK ADD  CONSTRAINT [FK_TA_DETALLEGUIAREMISION_TA_GUIAREMISION] FOREIGN KEY([INT_CODIGO_GUIA])
REFERENCES [dbo].[TA_GUIAREMISION] ([INT_CODIGO_GUIA])
GO
ALTER TABLE [dbo].[TA_DETALLEGUIAREMISION] CHECK CONSTRAINT [FK_TA_DETALLEGUIAREMISION_TA_GUIAREMISION]
GO
/****** Object:  ForeignKey [FK_TA_DETALLEGUIAREMISION_TA_TIPO_CARGA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_DETALLEGUIAREMISION]  WITH CHECK ADD  CONSTRAINT [FK_TA_DETALLEGUIAREMISION_TA_TIPO_CARGA] FOREIGN KEY([INT_TIPO_CARGA])
REFERENCES [dbo].[TA_TIPO_CARGA] ([INT_TIPO_CARGA])
GO
ALTER TABLE [dbo].[TA_DETALLEGUIAREMISION] CHECK CONSTRAINT [FK_TA_DETALLEGUIAREMISION_TA_TIPO_CARGA]
GO
/****** Object:  ForeignKey [FK_dbo.TA_EDUCACIONES_dbo.TA_DETALLESHOJAVIDA_INT_CODIGODETALLEHOJAVIDA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_EDUCACIONES]  WITH CHECK ADD  CONSTRAINT [FK_dbo.TA_EDUCACIONES_dbo.TA_DETALLESHOJAVIDA_INT_CODIGODETALLEHOJAVIDA] FOREIGN KEY([INT_CODIGODETALLEHOJAVIDA])
REFERENCES [dbo].[TA_DETALLESHOJAVIDA] ([INT_CODIGODETALLEHOJAVIDA])
GO
ALTER TABLE [dbo].[TA_EDUCACIONES] CHECK CONSTRAINT [FK_dbo.TA_EDUCACIONES_dbo.TA_DETALLESHOJAVIDA_INT_CODIGODETALLEHOJAVIDA]
GO
/****** Object:  ForeignKey [FK_TA_EQUIPAJE_TA_BOLETO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_EQUIPAJE]  WITH CHECK ADD  CONSTRAINT [FK_TA_EQUIPAJE_TA_BOLETO] FOREIGN KEY([INT_CODIGOBOLETO])
REFERENCES [dbo].[TA_BOLETO] ([INT_CODIGOBOLETO])
GO
ALTER TABLE [dbo].[TA_EQUIPAJE] CHECK CONSTRAINT [FK_TA_EQUIPAJE_TA_BOLETO]
GO
/****** Object:  ForeignKey [FK_TA_EQUIPAJE_TA_TIPOETIQUETA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_EQUIPAJE]  WITH CHECK ADD  CONSTRAINT [FK_TA_EQUIPAJE_TA_TIPOETIQUETA] FOREIGN KEY([INT_CODIGOETIQUETA])
REFERENCES [dbo].[TA_TIPOETIQUETA] ([INT_CODIGOETIQUETA])
GO
ALTER TABLE [dbo].[TA_EQUIPAJE] CHECK CONSTRAINT [FK_TA_EQUIPAJE_TA_TIPOETIQUETA]
GO
/****** Object:  ForeignKey [FK_TA_EVALUACION_DESEMPENO_TA_PERSONA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_EVALUACION_DESEMPENO]  WITH CHECK ADD  CONSTRAINT [FK_TA_EVALUACION_DESEMPENO_TA_PERSONA] FOREIGN KEY([INT_CODIGOPERSONA])
REFERENCES [dbo].[TA_PERSONA] ([INT_CODIGOPERSONA])
GO
ALTER TABLE [dbo].[TA_EVALUACION_DESEMPENO] CHECK CONSTRAINT [FK_TA_EVALUACION_DESEMPENO_TA_PERSONA]
GO
/****** Object:  ForeignKey [FK_TA_EVALUACION_DESEMPENO_TA_PERSONA1]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_EVALUACION_DESEMPENO]  WITH CHECK ADD  CONSTRAINT [FK_TA_EVALUACION_DESEMPENO_TA_PERSONA1] FOREIGN KEY([INT_CODIGOEVALUADO])
REFERENCES [dbo].[TA_PERSONA] ([INT_CODIGOPERSONA])
GO
ALTER TABLE [dbo].[TA_EVALUACION_DESEMPENO] CHECK CONSTRAINT [FK_TA_EVALUACION_DESEMPENO_TA_PERSONA1]
GO
/****** Object:  ForeignKey [FK_dbo.TA_EXPERIENCIASLABORALES_dbo.TA_DETALLESHOJAVIDA_INT_CODIGODETALLEHOJAVIDA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_EXPERIENCIASLABORAL]  WITH CHECK ADD  CONSTRAINT [FK_dbo.TA_EXPERIENCIASLABORALES_dbo.TA_DETALLESHOJAVIDA_INT_CODIGODETALLEHOJAVIDA] FOREIGN KEY([INT_CODIGODETALLEHOJAVIDA])
REFERENCES [dbo].[TA_DETALLESHOJAVIDA] ([INT_CODIGODETALLEHOJAVIDA])
GO
ALTER TABLE [dbo].[TA_EXPERIENCIASLABORAL] CHECK CONSTRAINT [FK_dbo.TA_EXPERIENCIASLABORALES_dbo.TA_DETALLESHOJAVIDA_INT_CODIGODETALLEHOJAVIDA]
GO
/****** Object:  ForeignKey [FK_TA_FICHA_MOVIMIENTO_TA_ALMACEN]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_FICHA_MOVIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_TA_FICHA_MOVIMIENTO_TA_ALMACEN] FOREIGN KEY([INT_CODIGO_ALMACEN])
REFERENCES [dbo].[TA_ALMACEN] ([INT_CODIGO_ALMACEN])
GO
ALTER TABLE [dbo].[TA_FICHA_MOVIMIENTO] CHECK CONSTRAINT [FK_TA_FICHA_MOVIMIENTO_TA_ALMACEN]
GO
/****** Object:  ForeignKey [FK_TA_FICHA_MOVIMIENTO_TA_CARGA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_FICHA_MOVIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_TA_FICHA_MOVIMIENTO_TA_CARGA] FOREIGN KEY([INT_CODIGO_CARGA])
REFERENCES [dbo].[TA_CARGA] ([INT_CODIGO_CARGA])
GO
ALTER TABLE [dbo].[TA_FICHA_MOVIMIENTO] CHECK CONSTRAINT [FK_TA_FICHA_MOVIMIENTO_TA_CARGA]
GO
/****** Object:  ForeignKey [FK_TA_FICHA_MOVIMIENTO_TA_TIPO_MOVIMIENTO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_FICHA_MOVIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_TA_FICHA_MOVIMIENTO_TA_TIPO_MOVIMIENTO] FOREIGN KEY([INT_TIPO_MOVIMIENTO])
REFERENCES [dbo].[TA_TIPO_MOVIMIENTO] ([INT_TIPO_MOVIMIENTO])
GO
ALTER TABLE [dbo].[TA_FICHA_MOVIMIENTO] CHECK CONSTRAINT [FK_TA_FICHA_MOVIMIENTO_TA_TIPO_MOVIMIENTO]
GO
/****** Object:  ForeignKey [FK_TA_PASAJ_REFERENCE_TA_PERSO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_PASAJERO]  WITH CHECK ADD  CONSTRAINT [FK_TA_PASAJ_REFERENCE_TA_PERSO] FOREIGN KEY([INT_CODIGOPERSONA])
REFERENCES [dbo].[TA_PERSONA] ([INT_CODIGOPERSONA])
GO
ALTER TABLE [dbo].[TA_PASAJERO] CHECK CONSTRAINT [FK_TA_PASAJ_REFERENCE_TA_PERSO]
GO
/****** Object:  ForeignKey [FK_TA_PERSONA_TA_CARGO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_PERSONA]  WITH CHECK ADD  CONSTRAINT [FK_TA_PERSONA_TA_CARGO] FOREIGN KEY([INT_CODIGOCARGO])
REFERENCES [dbo].[TA_CARGO] ([INT_CODIGOCARGO])
GO
ALTER TABLE [dbo].[TA_PERSONA] CHECK CONSTRAINT [FK_TA_PERSONA_TA_CARGO]
GO
/****** Object:  ForeignKey [FK_TA_PERSONA_TA_TIPOSDOCUMENTO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_PERSONA]  WITH CHECK ADD  CONSTRAINT [FK_TA_PERSONA_TA_TIPOSDOCUMENTO] FOREIGN KEY([INT_CODIGOTIPODOCUMENTO])
REFERENCES [dbo].[TA_TIPOSDOCUMENTO] ([INT_CODIGOTIPODOCUMENTO])
GO
ALTER TABLE [dbo].[TA_PERSONA] CHECK CONSTRAINT [FK_TA_PERSONA_TA_TIPOSDOCUMENTO]
GO
/****** Object:  ForeignKey [FK_TA_PERSONA_TA_UBIGEO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_PERSONA]  WITH CHECK ADD  CONSTRAINT [FK_TA_PERSONA_TA_UBIGEO] FOREIGN KEY([INT_CODIGO_UBIGEO])
REFERENCES [dbo].[TA_UBIGEO] ([INT_CODIGO_UBIGEO])
GO
ALTER TABLE [dbo].[TA_PERSONA] CHECK CONSTRAINT [FK_TA_PERSONA_TA_UBIGEO]
GO
/****** Object:  ForeignKey [FK_TA_PROGRAMACION_RUTA_TA_PERSONA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_PROGRAMACION_RUTA]  WITH CHECK ADD  CONSTRAINT [FK_TA_PROGRAMACION_RUTA_TA_PERSONA] FOREIGN KEY([INT_CODIGOPERSONA])
REFERENCES [dbo].[TA_PERSONA] ([INT_CODIGOPERSONA])
GO
ALTER TABLE [dbo].[TA_PROGRAMACION_RUTA] CHECK CONSTRAINT [FK_TA_PROGRAMACION_RUTA_TA_PERSONA]
GO
/****** Object:  ForeignKey [FK_TA_PROGRAMACION_RUTA_TA_RUTA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_PROGRAMACION_RUTA]  WITH CHECK ADD  CONSTRAINT [FK_TA_PROGRAMACION_RUTA_TA_RUTA] FOREIGN KEY([INT_CODIGO_RUTA])
REFERENCES [dbo].[TA_RUTA] ([INT_CODIGO_RUTA])
GO
ALTER TABLE [dbo].[TA_PROGRAMACION_RUTA] CHECK CONSTRAINT [FK_TA_PROGRAMACION_RUTA_TA_RUTA]
GO
/****** Object:  ForeignKey [FK_TA_PROGRAMACION_RUTA_TA_TIPO_SERVICIO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_PROGRAMACION_RUTA]  WITH CHECK ADD  CONSTRAINT [FK_TA_PROGRAMACION_RUTA_TA_TIPO_SERVICIO] FOREIGN KEY([INT_TIPO_SERVICIO])
REFERENCES [dbo].[TA_TIPO_SERVICIO] ([INT_CODIGOTIPOSERVICIO])
GO
ALTER TABLE [dbo].[TA_PROGRAMACION_RUTA] CHECK CONSTRAINT [FK_TA_PROGRAMACION_RUTA_TA_TIPO_SERVICIO]
GO
/****** Object:  ForeignKey [FK_TA_PROGRAMACION_RUTA_TA_VEHICULO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_PROGRAMACION_RUTA]  WITH CHECK ADD  CONSTRAINT [FK_TA_PROGRAMACION_RUTA_TA_VEHICULO] FOREIGN KEY([INT_CODIGOVEHICULO])
REFERENCES [dbo].[TA_VEHICULO] ([INT_VEHICULO])
GO
ALTER TABLE [dbo].[TA_PROGRAMACION_RUTA] CHECK CONSTRAINT [FK_TA_PROGRAMACION_RUTA_TA_VEHICULO]
GO
/****** Object:  ForeignKey [FK_TA_RUTA_TA_AGENCIA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_RUTA]  WITH CHECK ADD  CONSTRAINT [FK_TA_RUTA_TA_AGENCIA] FOREIGN KEY([INT_CODIGO_AGENCIAORIGEN])
REFERENCES [dbo].[TA_AGENCIA] ([INT_CODIGO_AGENCIA])
GO
ALTER TABLE [dbo].[TA_RUTA] CHECK CONSTRAINT [FK_TA_RUTA_TA_AGENCIA]
GO
/****** Object:  ForeignKey [FK_TA_RUTA_TA_AGENCIA1]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_RUTA]  WITH CHECK ADD  CONSTRAINT [FK_TA_RUTA_TA_AGENCIA1] FOREIGN KEY([INT_CODIGO_AGENCIADESTINO])
REFERENCES [dbo].[TA_AGENCIA] ([INT_CODIGO_AGENCIA])
GO
ALTER TABLE [dbo].[TA_RUTA] CHECK CONSTRAINT [FK_TA_RUTA_TA_AGENCIA1]
GO
/****** Object:  ForeignKey [FK_TA_SOLICITUDCOCINA_TA_PROGRAMACION_RUTA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_SOLICITUDCOCINA]  WITH CHECK ADD  CONSTRAINT [FK_TA_SOLICITUDCOCINA_TA_PROGRAMACION_RUTA] FOREIGN KEY([INT_CODIGO_PROGRAMACION_RUTA])
REFERENCES [dbo].[TA_PROGRAMACION_RUTA] ([INT_CODIGO_PROGRAMACION_RUTA])
GO
ALTER TABLE [dbo].[TA_SOLICITUDCOCINA] CHECK CONSTRAINT [FK_TA_SOLICITUDCOCINA_TA_PROGRAMACION_RUTA]
GO
/****** Object:  ForeignKey [FK_TA_SOLICITUDCOCINA_TA_REFRIGERIO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_SOLICITUDCOCINA]  WITH CHECK ADD  CONSTRAINT [FK_TA_SOLICITUDCOCINA_TA_REFRIGERIO] FOREIGN KEY([INT_CODIGO_REFRIGERIO])
REFERENCES [dbo].[TA_REFRIGERIO] ([INT_CODIGO_REFRIGERIO])
GO
ALTER TABLE [dbo].[TA_SOLICITUDCOCINA] CHECK CONSTRAINT [FK_TA_SOLICITUDCOCINA_TA_REFRIGERIO]
GO
/****** Object:  ForeignKey [FK_dbo.TA_SOLICITUDESCAPACITACION_dbo.TA_SOLICITUDES_INT_CODIGOSOLICITUD]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_SOLICITUDESCAPACITACION]  WITH CHECK ADD  CONSTRAINT [FK_dbo.TA_SOLICITUDESCAPACITACION_dbo.TA_SOLICITUDES_INT_CODIGOSOLICITUD] FOREIGN KEY([INT_CODIGOSOLICITUD])
REFERENCES [dbo].[TA_SOLICITUDES] ([INT_CODIGOSOLICITUD])
GO
ALTER TABLE [dbo].[TA_SOLICITUDESCAPACITACION] CHECK CONSTRAINT [FK_dbo.TA_SOLICITUDESCAPACITACION_dbo.TA_SOLICITUDES_INT_CODIGOSOLICITUD]
GO
/****** Object:  ForeignKey [FK_TA_SOLICITUDESCAPACITACION_TA_PERSONA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_SOLICITUDESCAPACITACION]  WITH CHECK ADD  CONSTRAINT [FK_TA_SOLICITUDESCAPACITACION_TA_PERSONA] FOREIGN KEY([INT_CODIGOPERSONA])
REFERENCES [dbo].[TA_PERSONA] ([INT_CODIGOPERSONA])
GO
ALTER TABLE [dbo].[TA_SOLICITUDESCAPACITACION] CHECK CONSTRAINT [FK_TA_SOLICITUDESCAPACITACION_TA_PERSONA]
GO
/****** Object:  ForeignKey [FK_dbo.TA_SOLICITUDESPERSONAL_dbo.TA_SOLICITUDES_INT_CODIGOSOLICITUD]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_SOLICITUDESPERSONAL]  WITH CHECK ADD  CONSTRAINT [FK_dbo.TA_SOLICITUDESPERSONAL_dbo.TA_SOLICITUDES_INT_CODIGOSOLICITUD] FOREIGN KEY([INT_CODIGOSOLICITUD])
REFERENCES [dbo].[TA_SOLICITUDES] ([INT_CODIGOSOLICITUD])
GO
ALTER TABLE [dbo].[TA_SOLICITUDESPERSONAL] CHECK CONSTRAINT [FK_dbo.TA_SOLICITUDESPERSONAL_dbo.TA_SOLICITUDES_INT_CODIGOSOLICITUD]
GO
/****** Object:  ForeignKey [FK_TA_SOLICITUDINSUMO_TA_INSUMO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_SOLICITUDINSUMO]  WITH CHECK ADD  CONSTRAINT [FK_TA_SOLICITUDINSUMO_TA_INSUMO] FOREIGN KEY([INT_CODIGO_INSUMO])
REFERENCES [dbo].[TA_INSUMO] ([INT_CODIGO_INSUMO])
GO
ALTER TABLE [dbo].[TA_SOLICITUDINSUMO] CHECK CONSTRAINT [FK_TA_SOLICITUDINSUMO_TA_INSUMO]
GO
/****** Object:  ForeignKey [FK_TA_SOLICITUDINSUMO_TA_SOLICITUDCOCINA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_SOLICITUDINSUMO]  WITH CHECK ADD  CONSTRAINT [FK_TA_SOLICITUDINSUMO_TA_SOLICITUDCOCINA] FOREIGN KEY([INT_CODIGO_SOLICITUDCOCINA])
REFERENCES [dbo].[TA_SOLICITUDCOCINA] ([INT_CODIGO_SOLICITUDCOCINA])
GO
ALTER TABLE [dbo].[TA_SOLICITUDINSUMO] CHECK CONSTRAINT [FK_TA_SOLICITUDINSUMO_TA_SOLICITUDCOCINA]
GO
/****** Object:  ForeignKey [FK_TA_SOLPRODUCTODECABINA_TA_PRODUCTO_CABINA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_SOLPRODUCTODECABINA]  WITH CHECK ADD  CONSTRAINT [FK_TA_SOLPRODUCTODECABINA_TA_PRODUCTO_CABINA] FOREIGN KEY([INT_CODIGO_PRODUCTOCABINA])
REFERENCES [dbo].[TA_PRODUCTO_CABINA] ([INT_CODIGO_PRODUCTOCABINA])
GO
ALTER TABLE [dbo].[TA_SOLPRODUCTODECABINA] CHECK CONSTRAINT [FK_TA_SOLPRODUCTODECABINA_TA_PRODUCTO_CABINA]
GO
/****** Object:  ForeignKey [FK_TA_SOLPRODUCTODECABINA_TA_PROGRAMACION_RUTA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_SOLPRODUCTODECABINA]  WITH CHECK ADD  CONSTRAINT [FK_TA_SOLPRODUCTODECABINA_TA_PROGRAMACION_RUTA] FOREIGN KEY([INT_CODIGO_PROGRAMACION_RUTA])
REFERENCES [dbo].[TA_PROGRAMACION_RUTA] ([INT_CODIGO_PROGRAMACION_RUTA])
GO
ALTER TABLE [dbo].[TA_SOLPRODUCTODECABINA] CHECK CONSTRAINT [FK_TA_SOLPRODUCTODECABINA_TA_PROGRAMACION_RUTA]
GO
/****** Object:  ForeignKey [FK_TA_STOCK_TA_ALMACEN]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_TA_STOCK_TA_ALMACEN] FOREIGN KEY([INT_CODIGO_PRODUCTOCABINA])
REFERENCES [dbo].[TA_ALMACEN] ([INT_CODIGO_ALMACEN])
GO
ALTER TABLE [dbo].[TA_STOCK] CHECK CONSTRAINT [FK_TA_STOCK_TA_ALMACEN]
GO
/****** Object:  ForeignKey [FK_TA_STOCK_TA_PRODUCTO_CABINA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_TA_STOCK_TA_PRODUCTO_CABINA] FOREIGN KEY([INT_CODIGO_PRODUCTOCABINA])
REFERENCES [dbo].[TA_PRODUCTO_CABINA] ([INT_CODIGO_PRODUCTOCABINA])
GO
ALTER TABLE [dbo].[TA_STOCK] CHECK CONSTRAINT [FK_TA_STOCK_TA_PRODUCTO_CABINA]
GO
/****** Object:  ForeignKey [FK_TA_TRAZABILIDADCARGA_TA_CARGA]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_TRAZABILIDADCARGA]  WITH CHECK ADD  CONSTRAINT [FK_TA_TRAZABILIDADCARGA_TA_CARGA] FOREIGN KEY([INT_CODIGO_CARGA])
REFERENCES [dbo].[TA_CARGA] ([INT_CODIGO_CARGA])
GO
ALTER TABLE [dbo].[TA_TRAZABILIDADCARGA] CHECK CONSTRAINT [FK_TA_TRAZABILIDADCARGA_TA_CARGA]
GO
/****** Object:  ForeignKey [FK_TA_USUARIO_TA_ROL]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_TA_USUARIO_TA_ROL] FOREIGN KEY([INT_CODIGO_ROL])
REFERENCES [dbo].[TA_ROL] ([INT_CODIGO_ROL])
GO
ALTER TABLE [dbo].[TA_USUARIO] CHECK CONSTRAINT [FK_TA_USUARIO_TA_ROL]
GO
/****** Object:  ForeignKey [FK_TA_USUARIO_TA_UBIGEO]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_TA_USUARIO_TA_UBIGEO] FOREIGN KEY([INT_CODIGO_UBIGEO])
REFERENCES [dbo].[TA_UBIGEO] ([INT_CODIGO_UBIGEO])
GO
ALTER TABLE [dbo].[TA_USUARIO] CHECK CONSTRAINT [FK_TA_USUARIO_TA_UBIGEO]
GO
/****** Object:  ForeignKey [FK_TA_VEHICULO_TA_TIPO_TRANSPORTE]    Script Date: 09/11/2014 19:59:43 ******/
ALTER TABLE [dbo].[TA_VEHICULO]  WITH CHECK ADD  CONSTRAINT [FK_TA_VEHICULO_TA_TIPO_TRANSPORTE] FOREIGN KEY([INT_TIPO_TRANSPORTE])
REFERENCES [dbo].[TA_TIPO_TRANSPORTE] ([INT_TIPO_TRANSPORTE])
GO
ALTER TABLE [dbo].[TA_VEHICULO] CHECK CONSTRAINT [FK_TA_VEHICULO_TA_TIPO_TRANSPORTE]
GO
--
