//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:13
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMG_ES02_DetalleFCarga
    {
 
        public String Producto { get; set; }

 
        public String Descripcion { get; set; }

 
        public String TipoCarga { get; set; }

 
        public Int32 Cantidad { get; set; }

 
        public Double Peso { get; set; }

 
        public Double Importe { get; set; }

 
        public Int32 MG_ES01_FichaCarga_T_MG_ES01_FichaCarga_ID { get; set; }

 
        public BEMG_ES01_FichaCarga MG_ES01_FichaCarga { get; set; }

 
        public BEMG_ES01_FichaCarga MG_ES01_FichaCarga1 { get; set; }

 
        public BEMG_ES03_Producto MG_ES03_Producto { get; set; }

        public int MG_ES01_FichaCarga_ID { get; set; }
        public int MG_ES03_Producto_ID { get; set; }


        public BEMG_ES02_DetalleFCarga()
        {
        }

        public BEMG_ES02_DetalleFCarga(String producto, String descripcion, String tipoCarga, Int32 cantidad, Double peso, Double importe, Int32 t_MG_ES01_FichaCarga_T_MG_ES01_FichaCarga_ID, BEMG_ES01_FichaCarga mG_ES01_FichaCarga, BEMG_ES01_FichaCarga mG_ES01_FichaCarga1, BEMG_ES03_Producto mG_ES03_Producto)
        {
			this.Producto = producto;
			this.Descripcion = descripcion;
			this.TipoCarga = tipoCarga;
			this.Cantidad = cantidad;
			this.Peso = peso;
			this.Importe = importe;
			this.MG_ES01_FichaCarga_T_MG_ES01_FichaCarga_ID = t_MG_ES01_FichaCarga_T_MG_ES01_FichaCarga_ID;
			this.MG_ES01_FichaCarga = mG_ES01_FichaCarga;
			this.MG_ES01_FichaCarga1 = mG_ES01_FichaCarga1;
			this.MG_ES03_Producto = mG_ES03_Producto;
        }
    }
}
