//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:14
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMG_ES04_Cliente
    {
 
        public Int32 NroCliente { get; set; }

 
        public String Documento { get; set; }

 
        public String TipoDocumento { get; set; }

 
        public String Nombres { get; set; }

 
        public String Apellidos { get; set; }

 
        public String Direccion { get; set; }

 
        public String Telefono { get; set; }

 
        public String TipoCliente { get; set; }

 
        public Int32 Puntaje { get; set; }

 
        public Int32 NroTarjeta { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegsitra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 MG_ES04_Cliente_ID { get; set; }

 
        public List<BEMG_ES01_FichaCarga> MG_ES01_FichaCarga { get; set; }

 
        public List<BEMG_ES01_FichaCarga> MG_ES01_FichaCarga1 { get; set; }

        public BEMG_ES04_Cliente()
        {
        }

        public BEMG_ES04_Cliente(Int32 nroCliente, String documento, String tipoDocumento, String nombres, String apellidos, String direccion, String telefono, String tipoCliente, Int32 puntaje, Int32 nroTarjeta, DateTime fechaRegistra, String usuarioRegsitra, DateTime fechaModifica, String usuarioModifica, Int32 t_MG_ES04_Cliente_ID, List<BEMG_ES01_FichaCarga> mG_ES01_FichaCarga, List<BEMG_ES01_FichaCarga> mG_ES01_FichaCarga1)
        {
			this.NroCliente = nroCliente;
			this.Documento = documento;
			this.TipoDocumento = tipoDocumento;
			this.Nombres = nombres;
			this.Apellidos = apellidos;
			this.Direccion = direccion;
			this.Telefono = telefono;
			this.TipoCliente = tipoCliente;
			this.Puntaje = puntaje;
			this.NroTarjeta = nroTarjeta;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegsitra = usuarioRegsitra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.MG_ES04_Cliente_ID = t_MG_ES04_Cliente_ID;
			this.MG_ES01_FichaCarga = mG_ES01_FichaCarga;
			this.MG_ES01_FichaCarga1 = mG_ES01_FichaCarga1;
        }
    }
}
