//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:18
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMG_ES10_Agencia
    {
 
        public String Agencia { get; set; }

 
        public String Direccion { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MG_ES10_Agencia_ID { get; set; }

 
        public BEMG_ES07_Almacen MG_ES07_Almacen { get; set; }

 
        public BEMK_RutaBE MK_Ruta { get; set; }

 
        public List<BEMK_RutaBE> MK_Ruta1 { get; set; }

 
        public List<BEMK_RutaBE> MK_Ruta2 { get; set; }

        public BEMG_ES10_Agencia()
        {
        }

        public BEMG_ES10_Agencia(String agencia, String direccion, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MG_ES10_Agencia_ID, BEMG_ES07_Almacen mG_ES07_Almacen, BEMK_RutaBE mK_Ruta, List<BEMK_RutaBE> mK_Ruta1, List<BEMK_RutaBE> mK_Ruta2)
        {
			this.Agencia = agencia;
			this.Direccion = direccion;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MG_ES10_Agencia_ID = t_MG_ES10_Agencia_ID;
			this.MG_ES07_Almacen = mG_ES07_Almacen;
			this.MK_Ruta = mK_Ruta;
			this.MK_Ruta1 = mK_Ruta1;
			this.MK_Ruta2 = mK_Ruta2;
        }
    }
}
