//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:16
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMG_ES06_FichaMovimiento
    {
 
        public String Movimiento { get; set; }

 
        public DateTime FechaHora { get; set; }

 
        public String Tipo { get; set; }

 
        public String Observacion { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MG_ES06_FichaMovimiento_ID { get; set; }

 
        public BEMG_ES01_FichaCarga MG_ES01_FichaCarga { get; set; }

 
        public BEMG_ES07_Almacen MG_ES07_Almacen { get; set; }

        public BEMG_ES06_FichaMovimiento()
        {
        }

        public BEMG_ES06_FichaMovimiento(String movimiento, DateTime fechaHora, String tipo, String observacion, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MG_ES06_FichaMovimiento_ID, BEMG_ES01_FichaCarga mG_ES01_FichaCarga, BEMG_ES07_Almacen mG_ES07_Almacen)
        {
			this.Movimiento = movimiento;
			this.FechaHora = fechaHora;
			this.Tipo = tipo;
			this.Observacion = observacion;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MG_ES06_FichaMovimiento_ID = t_MG_ES06_FichaMovimiento_ID;
			this.MG_ES01_FichaCarga = mG_ES01_FichaCarga;
			this.MG_ES07_Almacen = mG_ES07_Almacen;
        }
    }
}
