//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:15
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMG_ES05_TrazabilidadCarga
    {
 
        public DateTime FechaRegistro { get; set; }

 
        public String EstadoCarga { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MG_ES05_TrazabilidadCarga_ID { get; set; }

 
        public BEMG_ES01_FichaCarga MG_ES01_FichaCarga { get; set; }

        public BEMG_ES05_TrazabilidadCarga()
        {
        }

        public BEMG_ES05_TrazabilidadCarga(DateTime fechaRegistro, String estadoCarga, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MG_ES05_TrazabilidadCarga_ID, BEMG_ES01_FichaCarga mG_ES01_FichaCarga)
        {
			this.FechaRegistro = fechaRegistro;
			this.EstadoCarga = estadoCarga;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MG_ES05_TrazabilidadCarga_ID = t_MG_ES05_TrazabilidadCarga_ID;
			this.MG_ES01_FichaCarga = mG_ES01_FichaCarga;
        }
    }
}
