//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:14
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMG_ES03_Producto
    {
 
        public String Producto { get; set; }

 
        public String Descripcion { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 MG_ES03_Producto_ID { get; set; }

        public Double Precio { get; set; }

        //Campos que no pertenecen a la tabla
        public String TipoCarga { get; set; }

 
        public List<BEMG_ES02_DetalleFCarga> MG_ES02_DetalleFCarga { get; set; }

        public BEMG_ES03_Producto()
        {
        }

        public BEMG_ES03_Producto(String producto, String descripcion, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MG_ES03_Producto_ID, List<BEMG_ES02_DetalleFCarga> mG_ES02_DetalleFCarga)
        {
			this.Producto = producto;
			this.Descripcion = descripcion;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.MG_ES03_Producto_ID = t_MG_ES03_Producto_ID;
			this.MG_ES02_DetalleFCarga = mG_ES02_DetalleFCarga;
        }
    }
}
