//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:18
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMG_ES09_DetalleGuiaRemision
    {
 
        public String Producto { get; set; }

 
        public String Descripcion { get; set; }

 
        public String TipoCarga { get; set; }

 
        public Int32 Cantidad { get; set; }

 
        public Int32 T_MG_ES08_GuiaRemision_ID { get; set; }

 
        public Int32 T_MK_ProgramacionRuta_ID { get; set; }

 
        public BEMG_ES08_GuiaRemision MG_ES08_GuiaRemision { get; set; }

        public BEMG_ES09_DetalleGuiaRemision()
        {
        }

        public BEMG_ES09_DetalleGuiaRemision(String producto, String descripcion, String tipoCarga, Int32 cantidad, Int32 t_MG_ES08_GuiaRemision_ID, Int32 t_MK_ProgramacionRuta_ID, BEMG_ES08_GuiaRemision mG_ES08_GuiaRemision)
        {
			this.Producto = producto;
			this.Descripcion = descripcion;
			this.TipoCarga = tipoCarga;
			this.Cantidad = cantidad;
			this.T_MG_ES08_GuiaRemision_ID = t_MG_ES08_GuiaRemision_ID;
			this.T_MK_ProgramacionRuta_ID = t_MK_ProgramacionRuta_ID;
			this.MG_ES08_GuiaRemision = mG_ES08_GuiaRemision;
        }
    }
}
