//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:17
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMG_ES08_GuiaRemision
    {
 
        public String GuiaRemision { get; set; }

 
        public DateTime FechaTraslado { get; set; }

 
        public String PuntoPartida { get; set; }

 
        public String PuntoLlegada { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MG_ES08_GuiaRemision_ID { get; set; }

 
        public Int32 T_MK_ProgramacionRuta_ID { get; set; }

 
        public List<BEMG_ES01_FichaCarga> MG_ES01_FichaCarga { get; set; }

 
        public BEMK_Conductor MK_Conductor { get; set; }

 
        public BEMK_Conductor MK_Conductor1 { get; set; }

 
        public BEMG_ES09_DetalleGuiaRemision MG_ES09_DetalleGuiaRemision { get; set; }

        public BEMG_ES08_GuiaRemision()
        {
        }

        public BEMG_ES08_GuiaRemision(String guiaRemision, DateTime fechaTraslado, String puntoPartida, String puntoLlegada, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MG_ES08_GuiaRemision_ID, Int32 t_MK_ProgramacionRuta_ID, List<BEMG_ES01_FichaCarga> mG_ES01_FichaCarga, BEMK_Conductor mK_Conductor, BEMK_Conductor mK_Conductor1, BEMG_ES09_DetalleGuiaRemision mG_ES09_DetalleGuiaRemision)
        {
			this.GuiaRemision = guiaRemision;
			this.FechaTraslado = fechaTraslado;
			this.PuntoPartida = puntoPartida;
			this.PuntoLlegada = puntoLlegada;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MG_ES08_GuiaRemision_ID = t_MG_ES08_GuiaRemision_ID;
			this.T_MK_ProgramacionRuta_ID = t_MK_ProgramacionRuta_ID;
			this.MG_ES01_FichaCarga = mG_ES01_FichaCarga;
			this.MK_Conductor = mK_Conductor;
			this.MK_Conductor1 = mK_Conductor1;
			this.MG_ES09_DetalleGuiaRemision = mG_ES09_DetalleGuiaRemision;
        }
    }
}
