//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
 
    public class BEMG_ES01_FichaCarga
    {
 
        public String Ficha { get; set; }

 
        public DateTime FechaRegistro { get; set; }

 
        public String Remitente { get; set; }

 
        public Int32 RemiDni { get; set; }

 
        public String Destinatario { get; set; }

 
        public Int32 DestiDni { get; set; }

 
        public Double PesoTotal { get; set; }

 
        public String TipoPago { get; set; }

 
        public Double ImporteTotal { get; set; }

 
        public String Observacion { get; set; }

 
        public Boolean EstadoPago { get; set; }

 
        public String ClaveSeguridad { get; set; }

 
        public String Estado { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 MG_ES01_FichaCarga_ID { get; set; }

 
        public BEMG_ES04_Cliente MG_ES04_Cliente { get; set; }

 
        public BEMG_ES04_Cliente MG_ES04_Cliente1 { get; set; }

 
        public BEMG_ES08_GuiaRemision MG_ES08_GuiaRemision { get; set; }

 
        public List<BEMG_ES02_DetalleFCarga> MG_ES02_DetalleFCarga { get; set; }

 
        public BEMG_ES02_DetalleFCarga MG_ES02_DetalleFCarga1 { get; set; }

 
        public List<BEMG_ES05_TrazabilidadCarga> MG_ES05_TrazabilidadCarga { get; set; }

 
        public List<BEMG_ES06_FichaMovimiento> MG_ES06_FichaMovimiento { get; set; }


        public Int32 MG_ES04_Cliente_ID { get; set; }
        public Int32 MG_ES04_Cliente_T_MG_ES04_Cliente_ID { get; set; }


        public Int32 MG_ES10_Agencia_IDOrigen { get; set; }
        public Int32 MG_ES10_Agencia_IDDestino { get; set; }
        public Int32 MK_ProgramacionRuta_ID  { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }

        public DateTime FechaHoraOrigen { get; set; }
        public DateTime FechaHoraDestino { get; set; }
        
        


        public BEMG_ES01_FichaCarga()
        {
        }

        public BEMG_ES01_FichaCarga(String ficha, DateTime fechaRegistro, String remitente, Int16 remiDni, String destinatario, Int32 destiDni, Double pesoTotal, String tipoPago, Double importeTotal, String observacion, Boolean estadoPago, String claveSeguridad, String estado, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MG_ES01_FichaCarga_ID, BEMG_ES04_Cliente mG_ES04_Cliente, BEMG_ES04_Cliente mG_ES04_Cliente1, BEMG_ES08_GuiaRemision mG_ES08_GuiaRemision, List<BEMG_ES02_DetalleFCarga> mG_ES02_DetalleFCarga, BEMG_ES02_DetalleFCarga mG_ES02_DetalleFCarga1, List<BEMG_ES05_TrazabilidadCarga> mG_ES05_TrazabilidadCarga, List<BEMG_ES06_FichaMovimiento> mG_ES06_FichaMovimiento)
        {
			this.Ficha = ficha;
			this.FechaRegistro = fechaRegistro;
			this.Remitente = remitente;
			this.RemiDni = remiDni;
			this.Destinatario = destinatario;
			this.DestiDni = destiDni;
			this.PesoTotal = pesoTotal;
			this.TipoPago = tipoPago;
			this.ImporteTotal = importeTotal;
			this.Observacion = observacion;
			this.EstadoPago = estadoPago;
			this.ClaveSeguridad = claveSeguridad;
			this.Estado = estado;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.MG_ES01_FichaCarga_ID = t_MG_ES01_FichaCarga_ID;
			this.MG_ES04_Cliente = mG_ES04_Cliente;
			this.MG_ES04_Cliente1 = mG_ES04_Cliente1;
			this.MG_ES08_GuiaRemision = mG_ES08_GuiaRemision;
			this.MG_ES02_DetalleFCarga = mG_ES02_DetalleFCarga;
			this.MG_ES02_DetalleFCarga1 = mG_ES02_DetalleFCarga1;
			this.MG_ES05_TrazabilidadCarga = mG_ES05_TrazabilidadCarga;
			this.MG_ES06_FichaMovimiento = mG_ES06_FichaMovimiento;
        }
    }
}
