//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:17
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMG_ES07_Almacen
    {
 
        public String Almacen { get; set; }

 
        public String Descripcion { get; set; }

 
        public Int32 Capacidad { get; set; }

 
        public String Direccion { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MG_ES10_Agencia_ID { get; set; }

 
        public List<BEMG_ES06_FichaMovimiento> MG_ES06_FichaMovimiento { get; set; }

 
        public BEMG_ES10_Agencia MG_ES10_Agencia { get; set; }

        public BEMG_ES07_Almacen()
        {
        }

        public BEMG_ES07_Almacen(String almacen, String descripcion, Int32 capacidad, String direccion, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MG_ES10_Agencia_ID, List<BEMG_ES06_FichaMovimiento> mG_ES06_FichaMovimiento, BEMG_ES10_Agencia mG_ES10_Agencia)
        {
			this.Almacen = almacen;
			this.Descripcion = descripcion;
			this.Capacidad = capacidad;
			this.Direccion = direccion;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MG_ES10_Agencia_ID = t_MG_ES10_Agencia_ID;
			this.MG_ES06_FichaMovimiento = mG_ES06_FichaMovimiento;
			this.MG_ES10_Agencia = mG_ES10_Agencia;
        }
    }
}
