//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:21
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMK_RutaBE
    {
 
        public String Descripcion { get; set; }

 
        public String Origen { get; set; }

 
        public String Destino { get; set; }

 
        public Boolean Estado { get; set; }

 
        public Boolean Directo { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MK_Ruta_ID { get; set; }

 
        public List<BEMG_ES10_Agencia> MG_ES10_Agencia { get; set; }

 
        public BEMG_ES10_Agencia MG_ES10_Agencia1 { get; set; }

 
        public BEMG_ES10_Agencia MG_ES10_Agencia2 { get; set; }

 
        public List<BEMK_ProgramacionRuta> MK_ProgramacionRuta { get; set; }

        public BEMK_RutaBE()
        {
        }

        public BEMK_RutaBE(String descripcion, String origen, String destino, Boolean estado, Boolean directo, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MK_Ruta_ID, List<BEMG_ES10_Agencia> mG_ES10_Agencia, BEMG_ES10_Agencia mG_ES10_Agencia1, BEMG_ES10_Agencia mG_ES10_Agencia2, List<BEMK_ProgramacionRuta> mK_ProgramacionRuta)
        {
			this.Descripcion = descripcion;
			this.Origen = origen;
			this.Destino = destino;
			this.Estado = estado;
			this.Directo = directo;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MK_Ruta_ID = t_MK_Ruta_ID;
			this.MG_ES10_Agencia = mG_ES10_Agencia;
			this.MG_ES10_Agencia1 = mG_ES10_Agencia1;
			this.MG_ES10_Agencia2 = mG_ES10_Agencia2;
			this.MK_ProgramacionRuta = mK_ProgramacionRuta;
        }
    }
}
