//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMK_MarcaVehiculo
    {
 
        public String Descripcion { get; set; }

 
        public String Estado { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MK_MarcaVehiculo_ID { get; set; }

 
        public List<BEMK_Modelo> MK_Modelo { get; set; }

        public BEMK_MarcaVehiculo()
        {
        }

        public BEMK_MarcaVehiculo(String descripcion, String estado, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MK_MarcaVehiculo_ID, List<BEMK_Modelo> mK_Modelo)
        {
			this.Descripcion = descripcion;
			this.Estado = estado;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MK_MarcaVehiculo_ID = t_MK_MarcaVehiculo_ID;
			this.MK_Modelo = mK_Modelo;
        }
    }
}
