//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMK_Conductor
    {
 
        public String Categoria { get; set; }

 
        public String Nombres { get; set; }

 
        public String Apellidos { get; set; }

 
        public String Direccion { get; set; }

 
        public String Password { get; set; }

 
        public Int16 Correo { get; set; }

 
        public String NumeroBrevete { get; set; }

 
        public String Estado { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MK_Conductor_ID { get; set; }

 
        public List<BEMG_ES08_GuiaRemision> MG_ES08_GuiaRemision { get; set; }

 
        public List<BEMG_ES08_GuiaRemision> MG_ES08_GuiaRemision1 { get; set; }

 
        public BEMK_ProgramacionRuta MK_ProgramacionRuta { get; set; }

 
        public BEMK_ProgramacionRuta MK_ProgramacionRuta1 { get; set; }

        public BEMK_Conductor()
        {
        }

        public BEMK_Conductor(String categoria, String nombres, String apellidos, String direccion, String password, Int16 correo, String numeroBrevete, String estado, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MK_Conductor_ID, List<BEMG_ES08_GuiaRemision> mG_ES08_GuiaRemision, List<BEMG_ES08_GuiaRemision> mG_ES08_GuiaRemision1, BEMK_ProgramacionRuta mK_ProgramacionRuta, BEMK_ProgramacionRuta mK_ProgramacionRuta1)
        {
			this.Categoria = categoria;
			this.Nombres = nombres;
			this.Apellidos = apellidos;
			this.Direccion = direccion;
			this.Password = password;
			this.Correo = correo;
			this.NumeroBrevete = numeroBrevete;
			this.Estado = estado;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MK_Conductor_ID = t_MK_Conductor_ID;
			this.MG_ES08_GuiaRemision = mG_ES08_GuiaRemision;
			this.MG_ES08_GuiaRemision1 = mG_ES08_GuiaRemision1;
			this.MK_ProgramacionRuta = mK_ProgramacionRuta;
			this.MK_ProgramacionRuta1 = mK_ProgramacionRuta1;
        }
    }
}
