//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public  class BEMK_ProgramacionRuta
    {

        public DateTime FechaHoraOrigen { get; set; }


        public DateTime FechaHoraDestino { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 MK_ProgramacionRuta_ID { get; set; }

 
        public List<BEMK_Conductor> MK_Conductor { get; set; }

 
        public List<BEMK_Conductor> MK_Conductor1 { get; set; }

 
        public BEMK_RutaBE MK_Ruta { get; set; }

 
        public List<BEMK_UnidadTransporte> MK_UnidadTransporte { get; set; }

 
        public BEMK_UnidadTransporte MK_UnidadTransporte1 { get; set; }

        public Int32 MK_Ruta_ID { get; set; }

        public String Descripcion { get; set; }
        public String Origen { get; set; }
        public String Destino { get; set; }
        public Int32 MG_ES10_Agencia_ID { get; set; }
        public Int32 MG_ES10_Agencia_T_MG_ES10_Agencia_ID { get; set; }
        
        


        
        public BEMK_ProgramacionRuta()
        {
        }

        public BEMK_ProgramacionRuta(DateTime fechaHoraOrigen, DateTime fechaHoraDestino, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MK_ProgramacionRuta_ID, List<BEMK_Conductor> mK_Conductor, List<BEMK_Conductor> mK_Conductor1, BEMK_RutaBE mK_Ruta, List<BEMK_UnidadTransporte> mK_UnidadTransporte, BEMK_UnidadTransporte mK_UnidadTransporte1)
        {
			this.FechaHoraOrigen = fechaHoraOrigen;
			this.FechaHoraDestino = fechaHoraDestino;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.MK_ProgramacionRuta_ID = t_MK_ProgramacionRuta_ID;
			this.MK_Conductor = mK_Conductor;
			this.MK_Conductor1 = mK_Conductor1;
			this.MK_Ruta = mK_Ruta;
			this.MK_UnidadTransporte = mK_UnidadTransporte;
			this.MK_UnidadTransporte1 = mK_UnidadTransporte1;
        }
    }
}
