//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:21
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMK_UnidadTransporte
    {
 
        public String Placa { get; set; }

 
        public String Color { get; set; }

 
        public String TipoVehiculo { get; set; }

 
        public DateTime FechaIngreso { get; set; }

 
        public Int32 NroPasajeros { get; set; }

 
        public String NroSerieMotor { get; set; }

 
        public Int16 Estado { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MK_ProgramacionRuta_T_MK_ProgramacionRuta_ID { get; set; }

 
        public Int16 name { get; set; }

 
        public BEMK_ProgramacionRuta MK_ProgramacionRuta { get; set; }

 
        public BEMK_ProgramacionRuta MK_ProgramacionRuta1 { get; set; }

        public BEMK_UnidadTransporte()
        {
        }

        public BEMK_UnidadTransporte(String placa, String color, String tipoVehiculo, DateTime fechaIngreso, Int32 nroPasajeros, String nroSerieMotor, Int16 estado, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MK_ProgramacionRuta_T_MK_ProgramacionRuta_ID, Int16 name, BEMK_ProgramacionRuta mK_ProgramacionRuta, BEMK_ProgramacionRuta mK_ProgramacionRuta1)
        {
			this.Placa = placa;
			this.Color = color;
			this.TipoVehiculo = tipoVehiculo;
			this.FechaIngreso = fechaIngreso;
			this.NroPasajeros = nroPasajeros;
			this.NroSerieMotor = nroSerieMotor;
			this.Estado = estado;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MK_ProgramacionRuta_T_MK_ProgramacionRuta_ID = t_MK_ProgramacionRuta_T_MK_ProgramacionRuta_ID;
			this.name = name;
			this.MK_ProgramacionRuta = mK_ProgramacionRuta;
			this.MK_ProgramacionRuta1 = mK_ProgramacionRuta1;
        }
    }
}
