//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMK_Modelo
    {
 
        public String Descripcion { get; set; }

 
        public String Estado { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MK_Modelo_ID { get; set; }

 
        public Int32 T_MK_ProgramacionRuta_ID { get; set; }

 
        public BEMK_MarcaVehiculo MK_MarcaVehiculo { get; set; }

        public BEMK_Modelo()
        {
        }

        public BEMK_Modelo(String descripcion, String estado, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MK_Modelo_ID, Int32 t_MK_ProgramacionRuta_ID, BEMK_MarcaVehiculo mK_MarcaVehiculo)
        {
			this.Descripcion = descripcion;
			this.Estado = estado;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MK_Modelo_ID = t_MK_Modelo_ID;
			this.T_MK_ProgramacionRuta_ID = t_MK_ProgramacionRuta_ID;
			this.MK_MarcaVehiculo = mK_MarcaVehiculo;
        }
    }
}
