//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMS_Usuario
    {
 
        public String Usuario { get; set; }

 
        public String Email { get; set; }

 
        public String Login { get; set; }

 
        public String Password { get; set; }

 
        public Int32 Estado { get; set; }

 
        public Int32 LoginCount { get; set; }

 
        public DateTime FechaAnteriorLogin { get; set; }

 
        public DateTime FechaActualLogin { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MS_Usuario_ID { get; set; }

 
        public List<BEMS_Perfil_Usuario> MS_Perfil_Usuario { get; set; }

        public BEMS_Usuario()
        {
        }

        public BEMS_Usuario(String usuario, String email, String login, String password, Int32 estado, Int32 loginCount, DateTime fechaAnteriorLogin, DateTime fechaActualLogin, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MS_Usuario_ID, List<BEMS_Perfil_Usuario> mS_Perfil_Usuario)
        {
			this.Usuario = usuario;
			this.Email = email;
			this.Login = login;
			this.Password = password;
			this.Estado = estado;
			this.LoginCount = loginCount;
			this.FechaAnteriorLogin = fechaAnteriorLogin;
			this.FechaActualLogin = fechaActualLogin;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MS_Usuario_ID = t_MS_Usuario_ID;
			this.MS_Perfil_Usuario = mS_Perfil_Usuario;
        }
    }
}
