//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMS_Permisos
    {
 
        public String Descripcion { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 COL_1 { get; set; }

 
        public Int16 name { get; set; }

 
        public BEMS_Perfil_Usuario MS_Perfil_Usuario { get; set; }

 
        public BEMS_Perfil_Usuario MS_Perfil_Usuario1 { get; set; }

 
        public BEMS_Perfil_Usuario MS_Perfil_Usuario2 { get; set; }

        public BEMS_Permisos()
        {
        }

        public BEMS_Permisos(String descripcion, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 cOL_1, Int16 name, BEMS_Perfil_Usuario mS_Perfil_Usuario, BEMS_Perfil_Usuario mS_Perfil_Usuario1, BEMS_Perfil_Usuario mS_Perfil_Usuario2)
        {
			this.Descripcion = descripcion;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.COL_1 = cOL_1;
			this.name = name;
			this.MS_Perfil_Usuario = mS_Perfil_Usuario;
			this.MS_Perfil_Usuario1 = mS_Perfil_Usuario1;
			this.MS_Perfil_Usuario2 = mS_Perfil_Usuario2;
        }
    }
}
