//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/08/07 - 07:06:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UPC.CruzDelSur.Negocio.Modelo.Carga
{
    
    public partial class BEMS_Perfil_Usuario
    {
 
        public String Descripcion { get; set; }

 
        public DateTime FechaRegistra { get; set; }

 
        public String UsuarioRegistra { get; set; }

 
        public DateTime FechaModifica { get; set; }

 
        public String UsuarioModifica { get; set; }

 
        public Int32 T_MS_Perfil_Usuario_ID { get; set; }

 
        public BEMS_Usuario MS_Usuario { get; set; }

 
        public List<BEMS_Permisos> MS_Permisos { get; set; }

 
        public List<BEMS_Permisos> MS_Permisos1 { get; set; }

 
        public BEMS_Permisos MS_Permisos2 { get; set; }

        public BEMS_Perfil_Usuario()
        {
        }

        public BEMS_Perfil_Usuario(String descripcion, DateTime fechaRegistra, String usuarioRegistra, DateTime fechaModifica, String usuarioModifica, Int32 t_MS_Perfil_Usuario_ID, BEMS_Usuario mS_Usuario, List<BEMS_Permisos> mS_Permisos, List<BEMS_Permisos> mS_Permisos1, BEMS_Permisos mS_Permisos2)
        {
			this.Descripcion = descripcion;
			this.FechaRegistra = fechaRegistra;
			this.UsuarioRegistra = usuarioRegistra;
			this.FechaModifica = fechaModifica;
			this.UsuarioModifica = usuarioModifica;
			this.T_MS_Perfil_Usuario_ID = t_MS_Perfil_Usuario_ID;
			this.MS_Usuario = mS_Usuario;
			this.MS_Permisos = mS_Permisos;
			this.MS_Permisos1 = mS_Permisos1;
			this.MS_Permisos2 = mS_Permisos2;
        }
    }
}
